// Code generated by go-swagger; DO NOT EDIT.

package policy_set_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteRuleInPolicySetUsingDELETE1Reader is a Reader for the DeleteRuleInPolicySetUsingDELETE1 structure.
type DeleteRuleInPolicySetUsingDELETE1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRuleInPolicySetUsingDELETE1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteRuleInPolicySetUsingDELETE1NoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteRuleInPolicySetUsingDELETE1BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteRuleInPolicySetUsingDELETE1Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteRuleInPolicySetUsingDELETE1Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDeleteRuleInPolicySetUsingDELETE1TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteRuleInPolicySetUsingDELETE1NoContent creates a DeleteRuleInPolicySetUsingDELETE1NoContent with default headers values
func NewDeleteRuleInPolicySetUsingDELETE1NoContent() *DeleteRuleInPolicySetUsingDELETE1NoContent {
	return &DeleteRuleInPolicySetUsingDELETE1NoContent{}
}

/* DeleteRuleInPolicySetUsingDELETE1NoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteRuleInPolicySetUsingDELETE1NoContent struct {
}

func (o *DeleteRuleInPolicySetUsingDELETE1NoContent) Error() string {
	return fmt.Sprintf("[DELETE /mgmtconfig/v1/admin/customers/{customerId}/policySet/{policySetId}/rule/{ruleId}][%d] deleteRuleInPolicySetUsingDELETE1NoContent ", 204)
}

func (o *DeleteRuleInPolicySetUsingDELETE1NoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRuleInPolicySetUsingDELETE1BadRequest creates a DeleteRuleInPolicySetUsingDELETE1BadRequest with default headers values
func NewDeleteRuleInPolicySetUsingDELETE1BadRequest() *DeleteRuleInPolicySetUsingDELETE1BadRequest {
	return &DeleteRuleInPolicySetUsingDELETE1BadRequest{}
}

/* DeleteRuleInPolicySetUsingDELETE1BadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type DeleteRuleInPolicySetUsingDELETE1BadRequest struct {
}

func (o *DeleteRuleInPolicySetUsingDELETE1BadRequest) Error() string {
	return fmt.Sprintf("[DELETE /mgmtconfig/v1/admin/customers/{customerId}/policySet/{policySetId}/rule/{ruleId}][%d] deleteRuleInPolicySetUsingDELETE1BadRequest ", 400)
}

func (o *DeleteRuleInPolicySetUsingDELETE1BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRuleInPolicySetUsingDELETE1Unauthorized creates a DeleteRuleInPolicySetUsingDELETE1Unauthorized with default headers values
func NewDeleteRuleInPolicySetUsingDELETE1Unauthorized() *DeleteRuleInPolicySetUsingDELETE1Unauthorized {
	return &DeleteRuleInPolicySetUsingDELETE1Unauthorized{}
}

/* DeleteRuleInPolicySetUsingDELETE1Unauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteRuleInPolicySetUsingDELETE1Unauthorized struct {
}

func (o *DeleteRuleInPolicySetUsingDELETE1Unauthorized) Error() string {
	return fmt.Sprintf("[DELETE /mgmtconfig/v1/admin/customers/{customerId}/policySet/{policySetId}/rule/{ruleId}][%d] deleteRuleInPolicySetUsingDELETE1Unauthorized ", 401)
}

func (o *DeleteRuleInPolicySetUsingDELETE1Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRuleInPolicySetUsingDELETE1Forbidden creates a DeleteRuleInPolicySetUsingDELETE1Forbidden with default headers values
func NewDeleteRuleInPolicySetUsingDELETE1Forbidden() *DeleteRuleInPolicySetUsingDELETE1Forbidden {
	return &DeleteRuleInPolicySetUsingDELETE1Forbidden{}
}

/* DeleteRuleInPolicySetUsingDELETE1Forbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteRuleInPolicySetUsingDELETE1Forbidden struct {
}

func (o *DeleteRuleInPolicySetUsingDELETE1Forbidden) Error() string {
	return fmt.Sprintf("[DELETE /mgmtconfig/v1/admin/customers/{customerId}/policySet/{policySetId}/rule/{ruleId}][%d] deleteRuleInPolicySetUsingDELETE1Forbidden ", 403)
}

func (o *DeleteRuleInPolicySetUsingDELETE1Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRuleInPolicySetUsingDELETE1TooManyRequests creates a DeleteRuleInPolicySetUsingDELETE1TooManyRequests with default headers values
func NewDeleteRuleInPolicySetUsingDELETE1TooManyRequests() *DeleteRuleInPolicySetUsingDELETE1TooManyRequests {
	return &DeleteRuleInPolicySetUsingDELETE1TooManyRequests{}
}

/* DeleteRuleInPolicySetUsingDELETE1TooManyRequests describes a response with status code 429, with default header values.

TooManyRequest
*/
type DeleteRuleInPolicySetUsingDELETE1TooManyRequests struct {
}

func (o *DeleteRuleInPolicySetUsingDELETE1TooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /mgmtconfig/v1/admin/customers/{customerId}/policySet/{policySetId}/rule/{ruleId}][%d] deleteRuleInPolicySetUsingDELETE1TooManyRequests ", 429)
}

func (o *DeleteRuleInPolicySetUsingDELETE1TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
