// Code generated by go-swagger; DO NOT EDIT.

package policy_set_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRuleInPolicySetUsingGET1Params creates a new GetRuleInPolicySetUsingGET1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRuleInPolicySetUsingGET1Params() *GetRuleInPolicySetUsingGET1Params {
	return &GetRuleInPolicySetUsingGET1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRuleInPolicySetUsingGET1ParamsWithTimeout creates a new GetRuleInPolicySetUsingGET1Params object
// with the ability to set a timeout on a request.
func NewGetRuleInPolicySetUsingGET1ParamsWithTimeout(timeout time.Duration) *GetRuleInPolicySetUsingGET1Params {
	return &GetRuleInPolicySetUsingGET1Params{
		timeout: timeout,
	}
}

// NewGetRuleInPolicySetUsingGET1ParamsWithContext creates a new GetRuleInPolicySetUsingGET1Params object
// with the ability to set a context for a request.
func NewGetRuleInPolicySetUsingGET1ParamsWithContext(ctx context.Context) *GetRuleInPolicySetUsingGET1Params {
	return &GetRuleInPolicySetUsingGET1Params{
		Context: ctx,
	}
}

// NewGetRuleInPolicySetUsingGET1ParamsWithHTTPClient creates a new GetRuleInPolicySetUsingGET1Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetRuleInPolicySetUsingGET1ParamsWithHTTPClient(client *http.Client) *GetRuleInPolicySetUsingGET1Params {
	return &GetRuleInPolicySetUsingGET1Params{
		HTTPClient: client,
	}
}

/* GetRuleInPolicySetUsingGET1Params contains all the parameters to send to the API endpoint
   for the get rule in policy set using g e t 1 operation.

   Typically these are written to a http.Request.
*/
type GetRuleInPolicySetUsingGET1Params struct {

	/* CustomerID.

	   The unique identifier of the ZPA tenant.
	*/
	CustomerID string

	/* PolicySetID.

	   The unique identifier of the policy.
	*/
	PolicySetID string

	/* RuleID.

	   The unique identifier of a rule in a policy.
	*/
	RuleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get rule in policy set using g e t 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRuleInPolicySetUsingGET1Params) WithDefaults() *GetRuleInPolicySetUsingGET1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get rule in policy set using g e t 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRuleInPolicySetUsingGET1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get rule in policy set using g e t 1 params
func (o *GetRuleInPolicySetUsingGET1Params) WithTimeout(timeout time.Duration) *GetRuleInPolicySetUsingGET1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get rule in policy set using g e t 1 params
func (o *GetRuleInPolicySetUsingGET1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get rule in policy set using g e t 1 params
func (o *GetRuleInPolicySetUsingGET1Params) WithContext(ctx context.Context) *GetRuleInPolicySetUsingGET1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get rule in policy set using g e t 1 params
func (o *GetRuleInPolicySetUsingGET1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get rule in policy set using g e t 1 params
func (o *GetRuleInPolicySetUsingGET1Params) WithHTTPClient(client *http.Client) *GetRuleInPolicySetUsingGET1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get rule in policy set using g e t 1 params
func (o *GetRuleInPolicySetUsingGET1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the get rule in policy set using g e t 1 params
func (o *GetRuleInPolicySetUsingGET1Params) WithCustomerID(customerID string) *GetRuleInPolicySetUsingGET1Params {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the get rule in policy set using g e t 1 params
func (o *GetRuleInPolicySetUsingGET1Params) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WithPolicySetID adds the policySetID to the get rule in policy set using g e t 1 params
func (o *GetRuleInPolicySetUsingGET1Params) WithPolicySetID(policySetID string) *GetRuleInPolicySetUsingGET1Params {
	o.SetPolicySetID(policySetID)
	return o
}

// SetPolicySetID adds the policySetId to the get rule in policy set using g e t 1 params
func (o *GetRuleInPolicySetUsingGET1Params) SetPolicySetID(policySetID string) {
	o.PolicySetID = policySetID
}

// WithRuleID adds the ruleID to the get rule in policy set using g e t 1 params
func (o *GetRuleInPolicySetUsingGET1Params) WithRuleID(ruleID string) *GetRuleInPolicySetUsingGET1Params {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the get rule in policy set using g e t 1 params
func (o *GetRuleInPolicySetUsingGET1Params) SetRuleID(ruleID string) {
	o.RuleID = ruleID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRuleInPolicySetUsingGET1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerId
	if err := r.SetPathParam("customerId", o.CustomerID); err != nil {
		return err
	}

	// path param policySetId
	if err := r.SetPathParam("policySetId", o.PolicySetID); err != nil {
		return err
	}

	// path param ruleId
	if err := r.SetPathParam("ruleId", o.RuleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
