// Code generated by go-swagger; DO NOT EDIT.

package application_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteApplicationUsingDELETE1Params creates a new DeleteApplicationUsingDELETE1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteApplicationUsingDELETE1Params() *DeleteApplicationUsingDELETE1Params {
	return &DeleteApplicationUsingDELETE1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteApplicationUsingDELETE1ParamsWithTimeout creates a new DeleteApplicationUsingDELETE1Params object
// with the ability to set a timeout on a request.
func NewDeleteApplicationUsingDELETE1ParamsWithTimeout(timeout time.Duration) *DeleteApplicationUsingDELETE1Params {
	return &DeleteApplicationUsingDELETE1Params{
		timeout: timeout,
	}
}

// NewDeleteApplicationUsingDELETE1ParamsWithContext creates a new DeleteApplicationUsingDELETE1Params object
// with the ability to set a context for a request.
func NewDeleteApplicationUsingDELETE1ParamsWithContext(ctx context.Context) *DeleteApplicationUsingDELETE1Params {
	return &DeleteApplicationUsingDELETE1Params{
		Context: ctx,
	}
}

// NewDeleteApplicationUsingDELETE1ParamsWithHTTPClient creates a new DeleteApplicationUsingDELETE1Params object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteApplicationUsingDELETE1ParamsWithHTTPClient(client *http.Client) *DeleteApplicationUsingDELETE1Params {
	return &DeleteApplicationUsingDELETE1Params{
		HTTPClient: client,
	}
}

/* DeleteApplicationUsingDELETE1Params contains all the parameters to send to the API endpoint
   for the delete application using d e l e t e 1 operation.

   Typically these are written to a http.Request.
*/
type DeleteApplicationUsingDELETE1Params struct {

	/* ApplicationID.

	   The unique identifier of the Application Segment.
	*/
	ApplicationID string

	/* CustomerID.

	   The unique identifier of the ZPA tenant.
	*/
	CustomerID string

	/* ForceDelete.

	   Setting this field to true will delete the mapping between Application Segment and Segment Group
	*/
	ForceDelete *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete application using d e l e t e 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteApplicationUsingDELETE1Params) WithDefaults() *DeleteApplicationUsingDELETE1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete application using d e l e t e 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteApplicationUsingDELETE1Params) SetDefaults() {
	var (
		forceDeleteDefault = bool(false)
	)

	val := DeleteApplicationUsingDELETE1Params{
		ForceDelete: &forceDeleteDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the delete application using d e l e t e 1 params
func (o *DeleteApplicationUsingDELETE1Params) WithTimeout(timeout time.Duration) *DeleteApplicationUsingDELETE1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete application using d e l e t e 1 params
func (o *DeleteApplicationUsingDELETE1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete application using d e l e t e 1 params
func (o *DeleteApplicationUsingDELETE1Params) WithContext(ctx context.Context) *DeleteApplicationUsingDELETE1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete application using d e l e t e 1 params
func (o *DeleteApplicationUsingDELETE1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete application using d e l e t e 1 params
func (o *DeleteApplicationUsingDELETE1Params) WithHTTPClient(client *http.Client) *DeleteApplicationUsingDELETE1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete application using d e l e t e 1 params
func (o *DeleteApplicationUsingDELETE1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApplicationID adds the applicationID to the delete application using d e l e t e 1 params
func (o *DeleteApplicationUsingDELETE1Params) WithApplicationID(applicationID string) *DeleteApplicationUsingDELETE1Params {
	o.SetApplicationID(applicationID)
	return o
}

// SetApplicationID adds the applicationId to the delete application using d e l e t e 1 params
func (o *DeleteApplicationUsingDELETE1Params) SetApplicationID(applicationID string) {
	o.ApplicationID = applicationID
}

// WithCustomerID adds the customerID to the delete application using d e l e t e 1 params
func (o *DeleteApplicationUsingDELETE1Params) WithCustomerID(customerID string) *DeleteApplicationUsingDELETE1Params {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the delete application using d e l e t e 1 params
func (o *DeleteApplicationUsingDELETE1Params) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WithForceDelete adds the forceDelete to the delete application using d e l e t e 1 params
func (o *DeleteApplicationUsingDELETE1Params) WithForceDelete(forceDelete *bool) *DeleteApplicationUsingDELETE1Params {
	o.SetForceDelete(forceDelete)
	return o
}

// SetForceDelete adds the forceDelete to the delete application using d e l e t e 1 params
func (o *DeleteApplicationUsingDELETE1Params) SetForceDelete(forceDelete *bool) {
	o.ForceDelete = forceDelete
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteApplicationUsingDELETE1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param applicationId
	if err := r.SetPathParam("applicationId", o.ApplicationID); err != nil {
		return err
	}

	// path param customerId
	if err := r.SetPathParam("customerId", o.CustomerID); err != nil {
		return err
	}

	if o.ForceDelete != nil {

		// query param forceDelete
		var qrForceDelete bool

		if o.ForceDelete != nil {
			qrForceDelete = *o.ForceDelete
		}
		qForceDelete := swag.FormatBool(qrForceDelete)
		if qForceDelete != "" {

			if err := r.SetQueryParam("forceDelete", qForceDelete); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
