// Code generated by go-swagger; DO NOT EDIT.

package application_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haarchri/zpa-go-client/pkg/models"
)

// GetApplicationUsingGET1Reader is a Reader for the GetApplicationUsingGET1 structure.
type GetApplicationUsingGET1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetApplicationUsingGET1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApplicationUsingGET1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetApplicationUsingGET1BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetApplicationUsingGET1Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetApplicationUsingGET1Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetApplicationUsingGET1NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetApplicationUsingGET1TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetApplicationUsingGET1OK creates a GetApplicationUsingGET1OK with default headers values
func NewGetApplicationUsingGET1OK() *GetApplicationUsingGET1OK {
	return &GetApplicationUsingGET1OK{}
}

/* GetApplicationUsingGET1OK describes a response with status code 200, with default header values.

OK
*/
type GetApplicationUsingGET1OK struct {
	Payload *models.ApplicationResource
}

func (o *GetApplicationUsingGET1OK) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/application/{applicationId}][%d] getApplicationUsingGET1OK  %+v", 200, o.Payload)
}
func (o *GetApplicationUsingGET1OK) GetPayload() *models.ApplicationResource {
	return o.Payload
}

func (o *GetApplicationUsingGET1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApplicationResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationUsingGET1BadRequest creates a GetApplicationUsingGET1BadRequest with default headers values
func NewGetApplicationUsingGET1BadRequest() *GetApplicationUsingGET1BadRequest {
	return &GetApplicationUsingGET1BadRequest{}
}

/* GetApplicationUsingGET1BadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type GetApplicationUsingGET1BadRequest struct {
}

func (o *GetApplicationUsingGET1BadRequest) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/application/{applicationId}][%d] getApplicationUsingGET1BadRequest ", 400)
}

func (o *GetApplicationUsingGET1BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetApplicationUsingGET1Unauthorized creates a GetApplicationUsingGET1Unauthorized with default headers values
func NewGetApplicationUsingGET1Unauthorized() *GetApplicationUsingGET1Unauthorized {
	return &GetApplicationUsingGET1Unauthorized{}
}

/* GetApplicationUsingGET1Unauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetApplicationUsingGET1Unauthorized struct {
}

func (o *GetApplicationUsingGET1Unauthorized) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/application/{applicationId}][%d] getApplicationUsingGET1Unauthorized ", 401)
}

func (o *GetApplicationUsingGET1Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetApplicationUsingGET1Forbidden creates a GetApplicationUsingGET1Forbidden with default headers values
func NewGetApplicationUsingGET1Forbidden() *GetApplicationUsingGET1Forbidden {
	return &GetApplicationUsingGET1Forbidden{}
}

/* GetApplicationUsingGET1Forbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetApplicationUsingGET1Forbidden struct {
}

func (o *GetApplicationUsingGET1Forbidden) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/application/{applicationId}][%d] getApplicationUsingGET1Forbidden ", 403)
}

func (o *GetApplicationUsingGET1Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetApplicationUsingGET1NotFound creates a GetApplicationUsingGET1NotFound with default headers values
func NewGetApplicationUsingGET1NotFound() *GetApplicationUsingGET1NotFound {
	return &GetApplicationUsingGET1NotFound{}
}

/* GetApplicationUsingGET1NotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetApplicationUsingGET1NotFound struct {
}

func (o *GetApplicationUsingGET1NotFound) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/application/{applicationId}][%d] getApplicationUsingGET1NotFound ", 404)
}

func (o *GetApplicationUsingGET1NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetApplicationUsingGET1TooManyRequests creates a GetApplicationUsingGET1TooManyRequests with default headers values
func NewGetApplicationUsingGET1TooManyRequests() *GetApplicationUsingGET1TooManyRequests {
	return &GetApplicationUsingGET1TooManyRequests{}
}

/* GetApplicationUsingGET1TooManyRequests describes a response with status code 429, with default header values.

TooManyRequest
*/
type GetApplicationUsingGET1TooManyRequests struct {
}

func (o *GetApplicationUsingGET1TooManyRequests) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/application/{applicationId}][%d] getApplicationUsingGET1TooManyRequests ", 429)
}

func (o *GetApplicationUsingGET1TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
