// Code generated by go-swagger; DO NOT EDIT.

package idp_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetIdpUsingGET1Params creates a new GetIdpUsingGET1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetIdpUsingGET1Params() *GetIdpUsingGET1Params {
	return &GetIdpUsingGET1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetIdpUsingGET1ParamsWithTimeout creates a new GetIdpUsingGET1Params object
// with the ability to set a timeout on a request.
func NewGetIdpUsingGET1ParamsWithTimeout(timeout time.Duration) *GetIdpUsingGET1Params {
	return &GetIdpUsingGET1Params{
		timeout: timeout,
	}
}

// NewGetIdpUsingGET1ParamsWithContext creates a new GetIdpUsingGET1Params object
// with the ability to set a context for a request.
func NewGetIdpUsingGET1ParamsWithContext(ctx context.Context) *GetIdpUsingGET1Params {
	return &GetIdpUsingGET1Params{
		Context: ctx,
	}
}

// NewGetIdpUsingGET1ParamsWithHTTPClient creates a new GetIdpUsingGET1Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetIdpUsingGET1ParamsWithHTTPClient(client *http.Client) *GetIdpUsingGET1Params {
	return &GetIdpUsingGET1Params{
		HTTPClient: client,
	}
}

/* GetIdpUsingGET1Params contains all the parameters to send to the API endpoint
   for the get idp using g e t 1 operation.

   Typically these are written to a http.Request.
*/
type GetIdpUsingGET1Params struct {

	/* CustomerID.

	   The unique identifier of the ZPA tenant.
	*/
	CustomerID string

	/* ScimEnabled.

	   Returns all SCIM IdPs if set to true. Returns all non SCIM IdPs if set to false.
	*/
	ScimEnabled bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get idp using g e t 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIdpUsingGET1Params) WithDefaults() *GetIdpUsingGET1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get idp using g e t 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIdpUsingGET1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get idp using g e t 1 params
func (o *GetIdpUsingGET1Params) WithTimeout(timeout time.Duration) *GetIdpUsingGET1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get idp using g e t 1 params
func (o *GetIdpUsingGET1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get idp using g e t 1 params
func (o *GetIdpUsingGET1Params) WithContext(ctx context.Context) *GetIdpUsingGET1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get idp using g e t 1 params
func (o *GetIdpUsingGET1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get idp using g e t 1 params
func (o *GetIdpUsingGET1Params) WithHTTPClient(client *http.Client) *GetIdpUsingGET1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get idp using g e t 1 params
func (o *GetIdpUsingGET1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the get idp using g e t 1 params
func (o *GetIdpUsingGET1Params) WithCustomerID(customerID string) *GetIdpUsingGET1Params {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the get idp using g e t 1 params
func (o *GetIdpUsingGET1Params) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WithScimEnabled adds the scimEnabled to the get idp using g e t 1 params
func (o *GetIdpUsingGET1Params) WithScimEnabled(scimEnabled bool) *GetIdpUsingGET1Params {
	o.SetScimEnabled(scimEnabled)
	return o
}

// SetScimEnabled adds the scimEnabled to the get idp using g e t 1 params
func (o *GetIdpUsingGET1Params) SetScimEnabled(scimEnabled bool) {
	o.ScimEnabled = scimEnabled
}

// WriteToRequest writes these params to a swagger request
func (o *GetIdpUsingGET1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerId
	if err := r.SetPathParam("customerId", o.CustomerID); err != nil {
		return err
	}

	// query param scimEnabled
	qrScimEnabled := o.ScimEnabled
	qScimEnabled := swag.FormatBool(qrScimEnabled)

	if err := r.SetQueryParam("scimEnabled", qScimEnabled); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
