// Code generated by go-swagger; DO NOT EDIT.

package lss_config_controller_v_2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/haarchri/zpa-go-client/pkg/models"
)

// NewAddLssUsingPOST3Params creates a new AddLssUsingPOST3Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddLssUsingPOST3Params() *AddLssUsingPOST3Params {
	return &AddLssUsingPOST3Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddLssUsingPOST3ParamsWithTimeout creates a new AddLssUsingPOST3Params object
// with the ability to set a timeout on a request.
func NewAddLssUsingPOST3ParamsWithTimeout(timeout time.Duration) *AddLssUsingPOST3Params {
	return &AddLssUsingPOST3Params{
		timeout: timeout,
	}
}

// NewAddLssUsingPOST3ParamsWithContext creates a new AddLssUsingPOST3Params object
// with the ability to set a context for a request.
func NewAddLssUsingPOST3ParamsWithContext(ctx context.Context) *AddLssUsingPOST3Params {
	return &AddLssUsingPOST3Params{
		Context: ctx,
	}
}

// NewAddLssUsingPOST3ParamsWithHTTPClient creates a new AddLssUsingPOST3Params object
// with the ability to set a custom HTTPClient for a request.
func NewAddLssUsingPOST3ParamsWithHTTPClient(client *http.Client) *AddLssUsingPOST3Params {
	return &AddLssUsingPOST3Params{
		HTTPClient: client,
	}
}

/* AddLssUsingPOST3Params contains all the parameters to send to the API endpoint
   for the add lss using p o s t 3 operation.

   Typically these are written to a http.Request.
*/
type AddLssUsingPOST3Params struct {

	/* CustomerID.

	   The unique identifier of the ZPA tenant.
	*/
	CustomerID string

	/* LssResource.

	   The object of the LSS resource.
	*/
	LssResource *models.LssResource

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add lss using p o s t 3 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddLssUsingPOST3Params) WithDefaults() *AddLssUsingPOST3Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add lss using p o s t 3 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddLssUsingPOST3Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add lss using p o s t 3 params
func (o *AddLssUsingPOST3Params) WithTimeout(timeout time.Duration) *AddLssUsingPOST3Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add lss using p o s t 3 params
func (o *AddLssUsingPOST3Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add lss using p o s t 3 params
func (o *AddLssUsingPOST3Params) WithContext(ctx context.Context) *AddLssUsingPOST3Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add lss using p o s t 3 params
func (o *AddLssUsingPOST3Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add lss using p o s t 3 params
func (o *AddLssUsingPOST3Params) WithHTTPClient(client *http.Client) *AddLssUsingPOST3Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add lss using p o s t 3 params
func (o *AddLssUsingPOST3Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the add lss using p o s t 3 params
func (o *AddLssUsingPOST3Params) WithCustomerID(customerID string) *AddLssUsingPOST3Params {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the add lss using p o s t 3 params
func (o *AddLssUsingPOST3Params) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WithLssResource adds the lssResource to the add lss using p o s t 3 params
func (o *AddLssUsingPOST3Params) WithLssResource(lssResource *models.LssResource) *AddLssUsingPOST3Params {
	o.SetLssResource(lssResource)
	return o
}

// SetLssResource adds the lssResource to the add lss using p o s t 3 params
func (o *AddLssUsingPOST3Params) SetLssResource(lssResource *models.LssResource) {
	o.LssResource = lssResource
}

// WriteToRequest writes these params to a swagger request
func (o *AddLssUsingPOST3Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerId
	if err := r.SetPathParam("customerId", o.CustomerID); err != nil {
		return err
	}
	if o.LssResource != nil {
		if err := r.SetBodyParam(o.LssResource); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
