// Code generated by go-swagger; DO NOT EDIT.

package lss_config_controller_v_2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteLssUsingDELETE3Params creates a new DeleteLssUsingDELETE3Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteLssUsingDELETE3Params() *DeleteLssUsingDELETE3Params {
	return &DeleteLssUsingDELETE3Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteLssUsingDELETE3ParamsWithTimeout creates a new DeleteLssUsingDELETE3Params object
// with the ability to set a timeout on a request.
func NewDeleteLssUsingDELETE3ParamsWithTimeout(timeout time.Duration) *DeleteLssUsingDELETE3Params {
	return &DeleteLssUsingDELETE3Params{
		timeout: timeout,
	}
}

// NewDeleteLssUsingDELETE3ParamsWithContext creates a new DeleteLssUsingDELETE3Params object
// with the ability to set a context for a request.
func NewDeleteLssUsingDELETE3ParamsWithContext(ctx context.Context) *DeleteLssUsingDELETE3Params {
	return &DeleteLssUsingDELETE3Params{
		Context: ctx,
	}
}

// NewDeleteLssUsingDELETE3ParamsWithHTTPClient creates a new DeleteLssUsingDELETE3Params object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteLssUsingDELETE3ParamsWithHTTPClient(client *http.Client) *DeleteLssUsingDELETE3Params {
	return &DeleteLssUsingDELETE3Params{
		HTTPClient: client,
	}
}

/* DeleteLssUsingDELETE3Params contains all the parameters to send to the API endpoint
   for the delete lss using d e l e t e 3 operation.

   Typically these are written to a http.Request.
*/
type DeleteLssUsingDELETE3Params struct {

	/* CustomerID.

	   The unique identifier of the ZPA tenant.
	*/
	CustomerID string

	/* LssID.

	   The unique identifier of the LSS resource.
	*/
	LssID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete lss using d e l e t e 3 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteLssUsingDELETE3Params) WithDefaults() *DeleteLssUsingDELETE3Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete lss using d e l e t e 3 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteLssUsingDELETE3Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete lss using d e l e t e 3 params
func (o *DeleteLssUsingDELETE3Params) WithTimeout(timeout time.Duration) *DeleteLssUsingDELETE3Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete lss using d e l e t e 3 params
func (o *DeleteLssUsingDELETE3Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete lss using d e l e t e 3 params
func (o *DeleteLssUsingDELETE3Params) WithContext(ctx context.Context) *DeleteLssUsingDELETE3Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete lss using d e l e t e 3 params
func (o *DeleteLssUsingDELETE3Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete lss using d e l e t e 3 params
func (o *DeleteLssUsingDELETE3Params) WithHTTPClient(client *http.Client) *DeleteLssUsingDELETE3Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete lss using d e l e t e 3 params
func (o *DeleteLssUsingDELETE3Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the delete lss using d e l e t e 3 params
func (o *DeleteLssUsingDELETE3Params) WithCustomerID(customerID string) *DeleteLssUsingDELETE3Params {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the delete lss using d e l e t e 3 params
func (o *DeleteLssUsingDELETE3Params) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WithLssID adds the lssID to the delete lss using d e l e t e 3 params
func (o *DeleteLssUsingDELETE3Params) WithLssID(lssID string) *DeleteLssUsingDELETE3Params {
	o.SetLssID(lssID)
	return o
}

// SetLssID adds the lssId to the delete lss using d e l e t e 3 params
func (o *DeleteLssUsingDELETE3Params) SetLssID(lssID string) {
	o.LssID = lssID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLssUsingDELETE3Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerId
	if err := r.SetPathParam("customerId", o.CustomerID); err != nil {
		return err
	}

	// path param lssId
	if err := r.SetPathParam("lssId", o.LssID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
