// Code generated by go-swagger; DO NOT EDIT.

package lss_config_controller_v_2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStatusCodesUsingGET1Params creates a new GetStatusCodesUsingGET1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetStatusCodesUsingGET1Params() *GetStatusCodesUsingGET1Params {
	return &GetStatusCodesUsingGET1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetStatusCodesUsingGET1ParamsWithTimeout creates a new GetStatusCodesUsingGET1Params object
// with the ability to set a timeout on a request.
func NewGetStatusCodesUsingGET1ParamsWithTimeout(timeout time.Duration) *GetStatusCodesUsingGET1Params {
	return &GetStatusCodesUsingGET1Params{
		timeout: timeout,
	}
}

// NewGetStatusCodesUsingGET1ParamsWithContext creates a new GetStatusCodesUsingGET1Params object
// with the ability to set a context for a request.
func NewGetStatusCodesUsingGET1ParamsWithContext(ctx context.Context) *GetStatusCodesUsingGET1Params {
	return &GetStatusCodesUsingGET1Params{
		Context: ctx,
	}
}

// NewGetStatusCodesUsingGET1ParamsWithHTTPClient creates a new GetStatusCodesUsingGET1Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetStatusCodesUsingGET1ParamsWithHTTPClient(client *http.Client) *GetStatusCodesUsingGET1Params {
	return &GetStatusCodesUsingGET1Params{
		HTTPClient: client,
	}
}

/* GetStatusCodesUsingGET1Params contains all the parameters to send to the API endpoint
   for the get status codes using g e t 1 operation.

   Typically these are written to a http.Request.
*/
type GetStatusCodesUsingGET1Params struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get status codes using g e t 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStatusCodesUsingGET1Params) WithDefaults() *GetStatusCodesUsingGET1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get status codes using g e t 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStatusCodesUsingGET1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get status codes using g e t 1 params
func (o *GetStatusCodesUsingGET1Params) WithTimeout(timeout time.Duration) *GetStatusCodesUsingGET1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get status codes using g e t 1 params
func (o *GetStatusCodesUsingGET1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get status codes using g e t 1 params
func (o *GetStatusCodesUsingGET1Params) WithContext(ctx context.Context) *GetStatusCodesUsingGET1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get status codes using g e t 1 params
func (o *GetStatusCodesUsingGET1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get status codes using g e t 1 params
func (o *GetStatusCodesUsingGET1Params) WithHTTPClient(client *http.Client) *GetStatusCodesUsingGET1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get status codes using g e t 1 params
func (o *GetStatusCodesUsingGET1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetStatusCodesUsingGET1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
