// Code generated by go-swagger; DO NOT EDIT.

package service_edge_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/haarchri/zpa-go-client/pkg/models"
)

// NewBulkDeleteServiceEdgeUsingPOSTParams creates a new BulkDeleteServiceEdgeUsingPOSTParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBulkDeleteServiceEdgeUsingPOSTParams() *BulkDeleteServiceEdgeUsingPOSTParams {
	return &BulkDeleteServiceEdgeUsingPOSTParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBulkDeleteServiceEdgeUsingPOSTParamsWithTimeout creates a new BulkDeleteServiceEdgeUsingPOSTParams object
// with the ability to set a timeout on a request.
func NewBulkDeleteServiceEdgeUsingPOSTParamsWithTimeout(timeout time.Duration) *BulkDeleteServiceEdgeUsingPOSTParams {
	return &BulkDeleteServiceEdgeUsingPOSTParams{
		timeout: timeout,
	}
}

// NewBulkDeleteServiceEdgeUsingPOSTParamsWithContext creates a new BulkDeleteServiceEdgeUsingPOSTParams object
// with the ability to set a context for a request.
func NewBulkDeleteServiceEdgeUsingPOSTParamsWithContext(ctx context.Context) *BulkDeleteServiceEdgeUsingPOSTParams {
	return &BulkDeleteServiceEdgeUsingPOSTParams{
		Context: ctx,
	}
}

// NewBulkDeleteServiceEdgeUsingPOSTParamsWithHTTPClient creates a new BulkDeleteServiceEdgeUsingPOSTParams object
// with the ability to set a custom HTTPClient for a request.
func NewBulkDeleteServiceEdgeUsingPOSTParamsWithHTTPClient(client *http.Client) *BulkDeleteServiceEdgeUsingPOSTParams {
	return &BulkDeleteServiceEdgeUsingPOSTParams{
		HTTPClient: client,
	}
}

/* BulkDeleteServiceEdgeUsingPOSTParams contains all the parameters to send to the API endpoint
   for the bulk delete service edge using p o s t operation.

   Typically these are written to a http.Request.
*/
type BulkDeleteServiceEdgeUsingPOSTParams struct {

	/* BulkDeleteResource.

	   The resource for bulk deleting the Service Edges.
	*/
	BulkDeleteResource *models.BulkDeleteResource

	/* CustomerID.

	   The unique identifier of the ZPA tenant.
	*/
	CustomerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the bulk delete service edge using p o s t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BulkDeleteServiceEdgeUsingPOSTParams) WithDefaults() *BulkDeleteServiceEdgeUsingPOSTParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the bulk delete service edge using p o s t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BulkDeleteServiceEdgeUsingPOSTParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the bulk delete service edge using p o s t params
func (o *BulkDeleteServiceEdgeUsingPOSTParams) WithTimeout(timeout time.Duration) *BulkDeleteServiceEdgeUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the bulk delete service edge using p o s t params
func (o *BulkDeleteServiceEdgeUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the bulk delete service edge using p o s t params
func (o *BulkDeleteServiceEdgeUsingPOSTParams) WithContext(ctx context.Context) *BulkDeleteServiceEdgeUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the bulk delete service edge using p o s t params
func (o *BulkDeleteServiceEdgeUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the bulk delete service edge using p o s t params
func (o *BulkDeleteServiceEdgeUsingPOSTParams) WithHTTPClient(client *http.Client) *BulkDeleteServiceEdgeUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the bulk delete service edge using p o s t params
func (o *BulkDeleteServiceEdgeUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBulkDeleteResource adds the bulkDeleteResource to the bulk delete service edge using p o s t params
func (o *BulkDeleteServiceEdgeUsingPOSTParams) WithBulkDeleteResource(bulkDeleteResource *models.BulkDeleteResource) *BulkDeleteServiceEdgeUsingPOSTParams {
	o.SetBulkDeleteResource(bulkDeleteResource)
	return o
}

// SetBulkDeleteResource adds the bulkDeleteResource to the bulk delete service edge using p o s t params
func (o *BulkDeleteServiceEdgeUsingPOSTParams) SetBulkDeleteResource(bulkDeleteResource *models.BulkDeleteResource) {
	o.BulkDeleteResource = bulkDeleteResource
}

// WithCustomerID adds the customerID to the bulk delete service edge using p o s t params
func (o *BulkDeleteServiceEdgeUsingPOSTParams) WithCustomerID(customerID string) *BulkDeleteServiceEdgeUsingPOSTParams {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the bulk delete service edge using p o s t params
func (o *BulkDeleteServiceEdgeUsingPOSTParams) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WriteToRequest writes these params to a swagger request
func (o *BulkDeleteServiceEdgeUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.BulkDeleteResource != nil {
		if err := r.SetBodyParam(o.BulkDeleteResource); err != nil {
			return err
		}
	}

	// path param customerId
	if err := r.SetPathParam("customerId", o.CustomerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
