// Code generated by go-swagger; DO NOT EDIT.

package service_edge_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteServiceEdgeUsingDELETEParams creates a new DeleteServiceEdgeUsingDELETEParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteServiceEdgeUsingDELETEParams() *DeleteServiceEdgeUsingDELETEParams {
	return &DeleteServiceEdgeUsingDELETEParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteServiceEdgeUsingDELETEParamsWithTimeout creates a new DeleteServiceEdgeUsingDELETEParams object
// with the ability to set a timeout on a request.
func NewDeleteServiceEdgeUsingDELETEParamsWithTimeout(timeout time.Duration) *DeleteServiceEdgeUsingDELETEParams {
	return &DeleteServiceEdgeUsingDELETEParams{
		timeout: timeout,
	}
}

// NewDeleteServiceEdgeUsingDELETEParamsWithContext creates a new DeleteServiceEdgeUsingDELETEParams object
// with the ability to set a context for a request.
func NewDeleteServiceEdgeUsingDELETEParamsWithContext(ctx context.Context) *DeleteServiceEdgeUsingDELETEParams {
	return &DeleteServiceEdgeUsingDELETEParams{
		Context: ctx,
	}
}

// NewDeleteServiceEdgeUsingDELETEParamsWithHTTPClient creates a new DeleteServiceEdgeUsingDELETEParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteServiceEdgeUsingDELETEParamsWithHTTPClient(client *http.Client) *DeleteServiceEdgeUsingDELETEParams {
	return &DeleteServiceEdgeUsingDELETEParams{
		HTTPClient: client,
	}
}

/* DeleteServiceEdgeUsingDELETEParams contains all the parameters to send to the API endpoint
   for the delete service edge using d e l e t e operation.

   Typically these are written to a http.Request.
*/
type DeleteServiceEdgeUsingDELETEParams struct {

	/* CustomerID.

	   The unique identifier of the ZPA tenant.
	*/
	CustomerID string

	/* ServiceEdgeID.

	   The unique identifier of the Service Edge.
	*/
	ServiceEdgeID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete service edge using d e l e t e params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteServiceEdgeUsingDELETEParams) WithDefaults() *DeleteServiceEdgeUsingDELETEParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete service edge using d e l e t e params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteServiceEdgeUsingDELETEParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete service edge using d e l e t e params
func (o *DeleteServiceEdgeUsingDELETEParams) WithTimeout(timeout time.Duration) *DeleteServiceEdgeUsingDELETEParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete service edge using d e l e t e params
func (o *DeleteServiceEdgeUsingDELETEParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete service edge using d e l e t e params
func (o *DeleteServiceEdgeUsingDELETEParams) WithContext(ctx context.Context) *DeleteServiceEdgeUsingDELETEParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete service edge using d e l e t e params
func (o *DeleteServiceEdgeUsingDELETEParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete service edge using d e l e t e params
func (o *DeleteServiceEdgeUsingDELETEParams) WithHTTPClient(client *http.Client) *DeleteServiceEdgeUsingDELETEParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete service edge using d e l e t e params
func (o *DeleteServiceEdgeUsingDELETEParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the delete service edge using d e l e t e params
func (o *DeleteServiceEdgeUsingDELETEParams) WithCustomerID(customerID string) *DeleteServiceEdgeUsingDELETEParams {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the delete service edge using d e l e t e params
func (o *DeleteServiceEdgeUsingDELETEParams) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WithServiceEdgeID adds the serviceEdgeID to the delete service edge using d e l e t e params
func (o *DeleteServiceEdgeUsingDELETEParams) WithServiceEdgeID(serviceEdgeID string) *DeleteServiceEdgeUsingDELETEParams {
	o.SetServiceEdgeID(serviceEdgeID)
	return o
}

// SetServiceEdgeID adds the serviceEdgeId to the delete service edge using d e l e t e params
func (o *DeleteServiceEdgeUsingDELETEParams) SetServiceEdgeID(serviceEdgeID string) {
	o.ServiceEdgeID = serviceEdgeID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteServiceEdgeUsingDELETEParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerId
	if err := r.SetPathParam("customerId", o.CustomerID); err != nil {
		return err
	}

	// path param serviceEdgeId
	if err := r.SetPathParam("serviceEdgeId", o.ServiceEdgeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
