// Code generated by go-swagger; DO NOT EDIT.

package service_edge_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haarchri/zpa-go-client/pkg/models"
)

// GetAllServiceEdgesUsingGETReader is a Reader for the GetAllServiceEdgesUsingGET structure.
type GetAllServiceEdgesUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllServiceEdgesUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllServiceEdgesUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAllServiceEdgesUsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAllServiceEdgesUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAllServiceEdgesUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAllServiceEdgesUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetAllServiceEdgesUsingGETTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllServiceEdgesUsingGETOK creates a GetAllServiceEdgesUsingGETOK with default headers values
func NewGetAllServiceEdgesUsingGETOK() *GetAllServiceEdgesUsingGETOK {
	return &GetAllServiceEdgesUsingGETOK{}
}

/* GetAllServiceEdgesUsingGETOK describes a response with status code 200, with default header values.

OK
*/
type GetAllServiceEdgesUsingGETOK struct {
	Payload *models.PageListOfServiceEdge
}

func (o *GetAllServiceEdgesUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/serviceEdge][%d] getAllServiceEdgesUsingGETOK  %+v", 200, o.Payload)
}
func (o *GetAllServiceEdgesUsingGETOK) GetPayload() *models.PageListOfServiceEdge {
	return o.Payload
}

func (o *GetAllServiceEdgesUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PageListOfServiceEdge)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllServiceEdgesUsingGETBadRequest creates a GetAllServiceEdgesUsingGETBadRequest with default headers values
func NewGetAllServiceEdgesUsingGETBadRequest() *GetAllServiceEdgesUsingGETBadRequest {
	return &GetAllServiceEdgesUsingGETBadRequest{}
}

/* GetAllServiceEdgesUsingGETBadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type GetAllServiceEdgesUsingGETBadRequest struct {
}

func (o *GetAllServiceEdgesUsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/serviceEdge][%d] getAllServiceEdgesUsingGETBadRequest ", 400)
}

func (o *GetAllServiceEdgesUsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllServiceEdgesUsingGETUnauthorized creates a GetAllServiceEdgesUsingGETUnauthorized with default headers values
func NewGetAllServiceEdgesUsingGETUnauthorized() *GetAllServiceEdgesUsingGETUnauthorized {
	return &GetAllServiceEdgesUsingGETUnauthorized{}
}

/* GetAllServiceEdgesUsingGETUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAllServiceEdgesUsingGETUnauthorized struct {
}

func (o *GetAllServiceEdgesUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/serviceEdge][%d] getAllServiceEdgesUsingGETUnauthorized ", 401)
}

func (o *GetAllServiceEdgesUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllServiceEdgesUsingGETForbidden creates a GetAllServiceEdgesUsingGETForbidden with default headers values
func NewGetAllServiceEdgesUsingGETForbidden() *GetAllServiceEdgesUsingGETForbidden {
	return &GetAllServiceEdgesUsingGETForbidden{}
}

/* GetAllServiceEdgesUsingGETForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAllServiceEdgesUsingGETForbidden struct {
}

func (o *GetAllServiceEdgesUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/serviceEdge][%d] getAllServiceEdgesUsingGETForbidden ", 403)
}

func (o *GetAllServiceEdgesUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllServiceEdgesUsingGETNotFound creates a GetAllServiceEdgesUsingGETNotFound with default headers values
func NewGetAllServiceEdgesUsingGETNotFound() *GetAllServiceEdgesUsingGETNotFound {
	return &GetAllServiceEdgesUsingGETNotFound{}
}

/* GetAllServiceEdgesUsingGETNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAllServiceEdgesUsingGETNotFound struct {
}

func (o *GetAllServiceEdgesUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/serviceEdge][%d] getAllServiceEdgesUsingGETNotFound ", 404)
}

func (o *GetAllServiceEdgesUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllServiceEdgesUsingGETTooManyRequests creates a GetAllServiceEdgesUsingGETTooManyRequests with default headers values
func NewGetAllServiceEdgesUsingGETTooManyRequests() *GetAllServiceEdgesUsingGETTooManyRequests {
	return &GetAllServiceEdgesUsingGETTooManyRequests{}
}

/* GetAllServiceEdgesUsingGETTooManyRequests describes a response with status code 429, with default header values.

TooManyRequest
*/
type GetAllServiceEdgesUsingGETTooManyRequests struct {
}

func (o *GetAllServiceEdgesUsingGETTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/serviceEdge][%d] getAllServiceEdgesUsingGETTooManyRequests ", 429)
}

func (o *GetAllServiceEdgesUsingGETTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
