// Code generated by go-swagger; DO NOT EDIT.

package service_edge_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateServiceEdgeUsingPUTReader is a Reader for the UpdateServiceEdgeUsingPUT structure.
type UpdateServiceEdgeUsingPUTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateServiceEdgeUsingPUTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUpdateServiceEdgeUsingPUTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewUpdateServiceEdgeUsingPUTNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateServiceEdgeUsingPUTBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateServiceEdgeUsingPUTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateServiceEdgeUsingPUTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateServiceEdgeUsingPUTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewUpdateServiceEdgeUsingPUTTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateServiceEdgeUsingPUTCreated creates a UpdateServiceEdgeUsingPUTCreated with default headers values
func NewUpdateServiceEdgeUsingPUTCreated() *UpdateServiceEdgeUsingPUTCreated {
	return &UpdateServiceEdgeUsingPUTCreated{}
}

/* UpdateServiceEdgeUsingPUTCreated describes a response with status code 201, with default header values.

Created
*/
type UpdateServiceEdgeUsingPUTCreated struct {
}

func (o *UpdateServiceEdgeUsingPUTCreated) Error() string {
	return fmt.Sprintf("[PUT /mgmtconfig/v1/admin/customers/{customerId}/serviceEdge/{serviceEdgeId}][%d] updateServiceEdgeUsingPUTCreated ", 201)
}

func (o *UpdateServiceEdgeUsingPUTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateServiceEdgeUsingPUTNoContent creates a UpdateServiceEdgeUsingPUTNoContent with default headers values
func NewUpdateServiceEdgeUsingPUTNoContent() *UpdateServiceEdgeUsingPUTNoContent {
	return &UpdateServiceEdgeUsingPUTNoContent{}
}

/* UpdateServiceEdgeUsingPUTNoContent describes a response with status code 204, with default header values.

No Content
*/
type UpdateServiceEdgeUsingPUTNoContent struct {
}

func (o *UpdateServiceEdgeUsingPUTNoContent) Error() string {
	return fmt.Sprintf("[PUT /mgmtconfig/v1/admin/customers/{customerId}/serviceEdge/{serviceEdgeId}][%d] updateServiceEdgeUsingPUTNoContent ", 204)
}

func (o *UpdateServiceEdgeUsingPUTNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateServiceEdgeUsingPUTBadRequest creates a UpdateServiceEdgeUsingPUTBadRequest with default headers values
func NewUpdateServiceEdgeUsingPUTBadRequest() *UpdateServiceEdgeUsingPUTBadRequest {
	return &UpdateServiceEdgeUsingPUTBadRequest{}
}

/* UpdateServiceEdgeUsingPUTBadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type UpdateServiceEdgeUsingPUTBadRequest struct {
}

func (o *UpdateServiceEdgeUsingPUTBadRequest) Error() string {
	return fmt.Sprintf("[PUT /mgmtconfig/v1/admin/customers/{customerId}/serviceEdge/{serviceEdgeId}][%d] updateServiceEdgeUsingPUTBadRequest ", 400)
}

func (o *UpdateServiceEdgeUsingPUTBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateServiceEdgeUsingPUTUnauthorized creates a UpdateServiceEdgeUsingPUTUnauthorized with default headers values
func NewUpdateServiceEdgeUsingPUTUnauthorized() *UpdateServiceEdgeUsingPUTUnauthorized {
	return &UpdateServiceEdgeUsingPUTUnauthorized{}
}

/* UpdateServiceEdgeUsingPUTUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type UpdateServiceEdgeUsingPUTUnauthorized struct {
}

func (o *UpdateServiceEdgeUsingPUTUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /mgmtconfig/v1/admin/customers/{customerId}/serviceEdge/{serviceEdgeId}][%d] updateServiceEdgeUsingPUTUnauthorized ", 401)
}

func (o *UpdateServiceEdgeUsingPUTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateServiceEdgeUsingPUTForbidden creates a UpdateServiceEdgeUsingPUTForbidden with default headers values
func NewUpdateServiceEdgeUsingPUTForbidden() *UpdateServiceEdgeUsingPUTForbidden {
	return &UpdateServiceEdgeUsingPUTForbidden{}
}

/* UpdateServiceEdgeUsingPUTForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type UpdateServiceEdgeUsingPUTForbidden struct {
}

func (o *UpdateServiceEdgeUsingPUTForbidden) Error() string {
	return fmt.Sprintf("[PUT /mgmtconfig/v1/admin/customers/{customerId}/serviceEdge/{serviceEdgeId}][%d] updateServiceEdgeUsingPUTForbidden ", 403)
}

func (o *UpdateServiceEdgeUsingPUTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateServiceEdgeUsingPUTNotFound creates a UpdateServiceEdgeUsingPUTNotFound with default headers values
func NewUpdateServiceEdgeUsingPUTNotFound() *UpdateServiceEdgeUsingPUTNotFound {
	return &UpdateServiceEdgeUsingPUTNotFound{}
}

/* UpdateServiceEdgeUsingPUTNotFound describes a response with status code 404, with default header values.

Not Found
*/
type UpdateServiceEdgeUsingPUTNotFound struct {
}

func (o *UpdateServiceEdgeUsingPUTNotFound) Error() string {
	return fmt.Sprintf("[PUT /mgmtconfig/v1/admin/customers/{customerId}/serviceEdge/{serviceEdgeId}][%d] updateServiceEdgeUsingPUTNotFound ", 404)
}

func (o *UpdateServiceEdgeUsingPUTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateServiceEdgeUsingPUTTooManyRequests creates a UpdateServiceEdgeUsingPUTTooManyRequests with default headers values
func NewUpdateServiceEdgeUsingPUTTooManyRequests() *UpdateServiceEdgeUsingPUTTooManyRequests {
	return &UpdateServiceEdgeUsingPUTTooManyRequests{}
}

/* UpdateServiceEdgeUsingPUTTooManyRequests describes a response with status code 429, with default header values.

TooManyRequest
*/
type UpdateServiceEdgeUsingPUTTooManyRequests struct {
}

func (o *UpdateServiceEdgeUsingPUTTooManyRequests) Error() string {
	return fmt.Sprintf("[PUT /mgmtconfig/v1/admin/customers/{customerId}/serviceEdge/{serviceEdgeId}][%d] updateServiceEdgeUsingPUTTooManyRequests ", 429)
}

func (o *UpdateServiceEdgeUsingPUTTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
