// Code generated by go-swagger; DO NOT EDIT.

package posture_profile_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPostureProfileUsingGET1Params creates a new GetPostureProfileUsingGET1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPostureProfileUsingGET1Params() *GetPostureProfileUsingGET1Params {
	return &GetPostureProfileUsingGET1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPostureProfileUsingGET1ParamsWithTimeout creates a new GetPostureProfileUsingGET1Params object
// with the ability to set a timeout on a request.
func NewGetPostureProfileUsingGET1ParamsWithTimeout(timeout time.Duration) *GetPostureProfileUsingGET1Params {
	return &GetPostureProfileUsingGET1Params{
		timeout: timeout,
	}
}

// NewGetPostureProfileUsingGET1ParamsWithContext creates a new GetPostureProfileUsingGET1Params object
// with the ability to set a context for a request.
func NewGetPostureProfileUsingGET1ParamsWithContext(ctx context.Context) *GetPostureProfileUsingGET1Params {
	return &GetPostureProfileUsingGET1Params{
		Context: ctx,
	}
}

// NewGetPostureProfileUsingGET1ParamsWithHTTPClient creates a new GetPostureProfileUsingGET1Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetPostureProfileUsingGET1ParamsWithHTTPClient(client *http.Client) *GetPostureProfileUsingGET1Params {
	return &GetPostureProfileUsingGET1Params{
		HTTPClient: client,
	}
}

/* GetPostureProfileUsingGET1Params contains all the parameters to send to the API endpoint
   for the get posture profile using g e t 1 operation.

   Typically these are written to a http.Request.
*/
type GetPostureProfileUsingGET1Params struct {

	/* CustomerID.

	   The unique identifier of the ZPA tenant.
	*/
	CustomerID string

	/* ID.

	   The unique identifier of the posture profile.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get posture profile using g e t 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPostureProfileUsingGET1Params) WithDefaults() *GetPostureProfileUsingGET1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get posture profile using g e t 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPostureProfileUsingGET1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get posture profile using g e t 1 params
func (o *GetPostureProfileUsingGET1Params) WithTimeout(timeout time.Duration) *GetPostureProfileUsingGET1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get posture profile using g e t 1 params
func (o *GetPostureProfileUsingGET1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get posture profile using g e t 1 params
func (o *GetPostureProfileUsingGET1Params) WithContext(ctx context.Context) *GetPostureProfileUsingGET1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get posture profile using g e t 1 params
func (o *GetPostureProfileUsingGET1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get posture profile using g e t 1 params
func (o *GetPostureProfileUsingGET1Params) WithHTTPClient(client *http.Client) *GetPostureProfileUsingGET1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get posture profile using g e t 1 params
func (o *GetPostureProfileUsingGET1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the get posture profile using g e t 1 params
func (o *GetPostureProfileUsingGET1Params) WithCustomerID(customerID string) *GetPostureProfileUsingGET1Params {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the get posture profile using g e t 1 params
func (o *GetPostureProfileUsingGET1Params) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WithID adds the id to the get posture profile using g e t 1 params
func (o *GetPostureProfileUsingGET1Params) WithID(id string) *GetPostureProfileUsingGET1Params {
	o.SetID(id)
	return o
}

// SetID adds the id to the get posture profile using g e t 1 params
func (o *GetPostureProfileUsingGET1Params) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPostureProfileUsingGET1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerId
	if err := r.SetPathParam("customerId", o.CustomerID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
