// Code generated by go-swagger; DO NOT EDIT.

package provisioning_key_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haarchri/zpa-go-client/pkg/models"
)

// GetProvisioningKeyUsingGET1Reader is a Reader for the GetProvisioningKeyUsingGET1 structure.
type GetProvisioningKeyUsingGET1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProvisioningKeyUsingGET1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProvisioningKeyUsingGET1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProvisioningKeyUsingGET1BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetProvisioningKeyUsingGET1Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetProvisioningKeyUsingGET1Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetProvisioningKeyUsingGET1NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetProvisioningKeyUsingGET1TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetProvisioningKeyUsingGET1OK creates a GetProvisioningKeyUsingGET1OK with default headers values
func NewGetProvisioningKeyUsingGET1OK() *GetProvisioningKeyUsingGET1OK {
	return &GetProvisioningKeyUsingGET1OK{}
}

/* GetProvisioningKeyUsingGET1OK describes a response with status code 200, with default header values.

OK
*/
type GetProvisioningKeyUsingGET1OK struct {
	Payload *models.ProvisioningKey
}

func (o *GetProvisioningKeyUsingGET1OK) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/associationType/{associationType}/provisioningKey/{provisioningKeyId}][%d] getProvisioningKeyUsingGET1OK  %+v", 200, o.Payload)
}
func (o *GetProvisioningKeyUsingGET1OK) GetPayload() *models.ProvisioningKey {
	return o.Payload
}

func (o *GetProvisioningKeyUsingGET1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProvisioningKey)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningKeyUsingGET1BadRequest creates a GetProvisioningKeyUsingGET1BadRequest with default headers values
func NewGetProvisioningKeyUsingGET1BadRequest() *GetProvisioningKeyUsingGET1BadRequest {
	return &GetProvisioningKeyUsingGET1BadRequest{}
}

/* GetProvisioningKeyUsingGET1BadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type GetProvisioningKeyUsingGET1BadRequest struct {
}

func (o *GetProvisioningKeyUsingGET1BadRequest) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/associationType/{associationType}/provisioningKey/{provisioningKeyId}][%d] getProvisioningKeyUsingGET1BadRequest ", 400)
}

func (o *GetProvisioningKeyUsingGET1BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProvisioningKeyUsingGET1Unauthorized creates a GetProvisioningKeyUsingGET1Unauthorized with default headers values
func NewGetProvisioningKeyUsingGET1Unauthorized() *GetProvisioningKeyUsingGET1Unauthorized {
	return &GetProvisioningKeyUsingGET1Unauthorized{}
}

/* GetProvisioningKeyUsingGET1Unauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetProvisioningKeyUsingGET1Unauthorized struct {
}

func (o *GetProvisioningKeyUsingGET1Unauthorized) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/associationType/{associationType}/provisioningKey/{provisioningKeyId}][%d] getProvisioningKeyUsingGET1Unauthorized ", 401)
}

func (o *GetProvisioningKeyUsingGET1Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProvisioningKeyUsingGET1Forbidden creates a GetProvisioningKeyUsingGET1Forbidden with default headers values
func NewGetProvisioningKeyUsingGET1Forbidden() *GetProvisioningKeyUsingGET1Forbidden {
	return &GetProvisioningKeyUsingGET1Forbidden{}
}

/* GetProvisioningKeyUsingGET1Forbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetProvisioningKeyUsingGET1Forbidden struct {
}

func (o *GetProvisioningKeyUsingGET1Forbidden) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/associationType/{associationType}/provisioningKey/{provisioningKeyId}][%d] getProvisioningKeyUsingGET1Forbidden ", 403)
}

func (o *GetProvisioningKeyUsingGET1Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProvisioningKeyUsingGET1NotFound creates a GetProvisioningKeyUsingGET1NotFound with default headers values
func NewGetProvisioningKeyUsingGET1NotFound() *GetProvisioningKeyUsingGET1NotFound {
	return &GetProvisioningKeyUsingGET1NotFound{}
}

/* GetProvisioningKeyUsingGET1NotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetProvisioningKeyUsingGET1NotFound struct {
}

func (o *GetProvisioningKeyUsingGET1NotFound) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/associationType/{associationType}/provisioningKey/{provisioningKeyId}][%d] getProvisioningKeyUsingGET1NotFound ", 404)
}

func (o *GetProvisioningKeyUsingGET1NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProvisioningKeyUsingGET1TooManyRequests creates a GetProvisioningKeyUsingGET1TooManyRequests with default headers values
func NewGetProvisioningKeyUsingGET1TooManyRequests() *GetProvisioningKeyUsingGET1TooManyRequests {
	return &GetProvisioningKeyUsingGET1TooManyRequests{}
}

/* GetProvisioningKeyUsingGET1TooManyRequests describes a response with status code 429, with default header values.

TooManyRequest
*/
type GetProvisioningKeyUsingGET1TooManyRequests struct {
}

func (o *GetProvisioningKeyUsingGET1TooManyRequests) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/associationType/{associationType}/provisioningKey/{provisioningKeyId}][%d] getProvisioningKeyUsingGET1TooManyRequests ", 429)
}

func (o *GetProvisioningKeyUsingGET1TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
