// Code generated by go-swagger; DO NOT EDIT.

package provisioning_key_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/haarchri/zpa-go-client/pkg/models"
)

// NewUpdateProvisioningKeyUsingPUT1Params creates a new UpdateProvisioningKeyUsingPUT1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateProvisioningKeyUsingPUT1Params() *UpdateProvisioningKeyUsingPUT1Params {
	return &UpdateProvisioningKeyUsingPUT1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateProvisioningKeyUsingPUT1ParamsWithTimeout creates a new UpdateProvisioningKeyUsingPUT1Params object
// with the ability to set a timeout on a request.
func NewUpdateProvisioningKeyUsingPUT1ParamsWithTimeout(timeout time.Duration) *UpdateProvisioningKeyUsingPUT1Params {
	return &UpdateProvisioningKeyUsingPUT1Params{
		timeout: timeout,
	}
}

// NewUpdateProvisioningKeyUsingPUT1ParamsWithContext creates a new UpdateProvisioningKeyUsingPUT1Params object
// with the ability to set a context for a request.
func NewUpdateProvisioningKeyUsingPUT1ParamsWithContext(ctx context.Context) *UpdateProvisioningKeyUsingPUT1Params {
	return &UpdateProvisioningKeyUsingPUT1Params{
		Context: ctx,
	}
}

// NewUpdateProvisioningKeyUsingPUT1ParamsWithHTTPClient creates a new UpdateProvisioningKeyUsingPUT1Params object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateProvisioningKeyUsingPUT1ParamsWithHTTPClient(client *http.Client) *UpdateProvisioningKeyUsingPUT1Params {
	return &UpdateProvisioningKeyUsingPUT1Params{
		HTTPClient: client,
	}
}

/* UpdateProvisioningKeyUsingPUT1Params contains all the parameters to send to the API endpoint
   for the update provisioning key using p u t 1 operation.

   Typically these are written to a http.Request.
*/
type UpdateProvisioningKeyUsingPUT1Params struct {

	/* AssociationType.

	   Specifies the provisioning key type for App Connectors or ZPA Private Service Edges. The supported values are CONNECTOR_GRP and SERVICE_EDGE_GRP.
	*/
	AssociationType string

	/* CustomerID.

	   The unique identifier of the ZPA tenant.
	*/
	CustomerID string

	/* ProvisioningKey.

	   The object of the Provisioning Key.
	*/
	ProvisioningKey *models.ProvisioningKey

	/* ProvisioningKeyID.

	   The unique identifier of the Provisioning Key.
	*/
	ProvisioningKeyID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update provisioning key using p u t 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateProvisioningKeyUsingPUT1Params) WithDefaults() *UpdateProvisioningKeyUsingPUT1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update provisioning key using p u t 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateProvisioningKeyUsingPUT1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update provisioning key using p u t 1 params
func (o *UpdateProvisioningKeyUsingPUT1Params) WithTimeout(timeout time.Duration) *UpdateProvisioningKeyUsingPUT1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update provisioning key using p u t 1 params
func (o *UpdateProvisioningKeyUsingPUT1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update provisioning key using p u t 1 params
func (o *UpdateProvisioningKeyUsingPUT1Params) WithContext(ctx context.Context) *UpdateProvisioningKeyUsingPUT1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update provisioning key using p u t 1 params
func (o *UpdateProvisioningKeyUsingPUT1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update provisioning key using p u t 1 params
func (o *UpdateProvisioningKeyUsingPUT1Params) WithHTTPClient(client *http.Client) *UpdateProvisioningKeyUsingPUT1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update provisioning key using p u t 1 params
func (o *UpdateProvisioningKeyUsingPUT1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAssociationType adds the associationType to the update provisioning key using p u t 1 params
func (o *UpdateProvisioningKeyUsingPUT1Params) WithAssociationType(associationType string) *UpdateProvisioningKeyUsingPUT1Params {
	o.SetAssociationType(associationType)
	return o
}

// SetAssociationType adds the associationType to the update provisioning key using p u t 1 params
func (o *UpdateProvisioningKeyUsingPUT1Params) SetAssociationType(associationType string) {
	o.AssociationType = associationType
}

// WithCustomerID adds the customerID to the update provisioning key using p u t 1 params
func (o *UpdateProvisioningKeyUsingPUT1Params) WithCustomerID(customerID string) *UpdateProvisioningKeyUsingPUT1Params {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the update provisioning key using p u t 1 params
func (o *UpdateProvisioningKeyUsingPUT1Params) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WithProvisioningKey adds the provisioningKey to the update provisioning key using p u t 1 params
func (o *UpdateProvisioningKeyUsingPUT1Params) WithProvisioningKey(provisioningKey *models.ProvisioningKey) *UpdateProvisioningKeyUsingPUT1Params {
	o.SetProvisioningKey(provisioningKey)
	return o
}

// SetProvisioningKey adds the provisioningKey to the update provisioning key using p u t 1 params
func (o *UpdateProvisioningKeyUsingPUT1Params) SetProvisioningKey(provisioningKey *models.ProvisioningKey) {
	o.ProvisioningKey = provisioningKey
}

// WithProvisioningKeyID adds the provisioningKeyID to the update provisioning key using p u t 1 params
func (o *UpdateProvisioningKeyUsingPUT1Params) WithProvisioningKeyID(provisioningKeyID string) *UpdateProvisioningKeyUsingPUT1Params {
	o.SetProvisioningKeyID(provisioningKeyID)
	return o
}

// SetProvisioningKeyID adds the provisioningKeyId to the update provisioning key using p u t 1 params
func (o *UpdateProvisioningKeyUsingPUT1Params) SetProvisioningKeyID(provisioningKeyID string) {
	o.ProvisioningKeyID = provisioningKeyID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateProvisioningKeyUsingPUT1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param associationType
	if err := r.SetPathParam("associationType", o.AssociationType); err != nil {
		return err
	}

	// path param customerId
	if err := r.SetPathParam("customerId", o.CustomerID); err != nil {
		return err
	}
	if o.ProvisioningKey != nil {
		if err := r.SetBodyParam(o.ProvisioningKey); err != nil {
			return err
		}
	}

	// path param provisioningKeyId
	if err := r.SetPathParam("provisioningKeyId", o.ProvisioningKeyID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
