// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppPortRange app port range
//
// swagger:model AppPortRange
type AppPortRange struct {

	// from
	From string `json:"from,omitempty"`

	// to
	To string `json:"to,omitempty"`
}

// Validate validates this app port range
func (m *AppPortRange) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this app port range based on context it is used
func (m *AppPortRange) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppPortRange) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppPortRange) UnmarshalBinary(b []byte) error {
	var res AppPortRange
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
