// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CustomScopeRequestCustomerIds custom scope request customer ids
//
// swagger:model CustomScopeRequestCustomerIds
type CustomScopeRequestCustomerIds struct {

	// add customer ids
	AddCustomerIds []int64 `json:"addCustomerIds"`

	// delete customer ids
	DeleteCustomerIds []int64 `json:"deleteCustomerIds"`
}

// Validate validates this custom scope request customer ids
func (m *CustomScopeRequestCustomerIds) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this custom scope request customer ids based on context it is used
func (m *CustomScopeRequestCustomerIds) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustomScopeRequestCustomerIds) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustomScopeRequestCustomerIds) UnmarshalBinary(b []byte) error {
	var res CustomScopeRequestCustomerIds
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
