// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IdpCertDto idp cert dto
//
// swagger:model IdpCertDto
type IdpCertDto struct {

	// c name
	CName string `json:"cName,omitempty"`

	// certificate
	Certificate string `json:"certificate,omitempty"`

	// serial no
	SerialNo string `json:"serialNo,omitempty"`

	// valid from in sec
	ValidFromInSec string `json:"validFromInSec,omitempty"`

	// valid to in sec
	ValidToInSec string `json:"validToInSec,omitempty"`
}

// Validate validates this idp cert dto
func (m *IdpCertDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this idp cert dto based on context it is used
func (m *IdpCertDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IdpCertDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IdpCertDto) UnmarshalBinary(b []byte) error {
	var res IdpCertDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
