// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceProvider service provider
//
// swagger:model ServiceProvider
type ServiceProvider struct {

	// certificate Url
	CertificateURL string `json:"certificateUrl,omitempty"`

	// sp base Url
	SpBaseURL string `json:"spBaseUrl,omitempty"`

	// sp entity Id
	SpEntityID string `json:"spEntityId,omitempty"`

	// sp metadata Url
	SpMetadataURL string `json:"spMetadataUrl,omitempty"`

	// sp post Url
	SpPostURL string `json:"spPostUrl,omitempty"`
}

// Validate validates this service provider
func (m *ServiceProvider) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service provider based on context it is used
func (m *ServiceProvider) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceProvider) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceProvider) UnmarshalBinary(b []byte) error {
	var res ServiceProvider
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
