// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Version version
//
// swagger:model Version
type Version struct {

	// creation time
	CreationTime string `json:"creationTime,omitempty"`

	// customer Id
	CustomerID string `json:"customerId,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// modified by
	ModifiedBy string `json:"modifiedBy,omitempty"`

	// modified time
	ModifiedTime string `json:"modifiedTime,omitempty"`

	// platform
	Platform string `json:"platform,omitempty"`

	// restart after uptime in days
	RestartAfterUptimeInDays string `json:"restartAfterUptimeInDays,omitempty"`

	// role
	Role string `json:"role,omitempty"`

	// version
	Version string `json:"version,omitempty"`

	// version profile gid
	VersionProfileGid string `json:"version_profile_gid,omitempty"`
}

// Validate validates this version
func (m *Version) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this version based on context it is used
func (m *Version) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Version) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Version) UnmarshalBinary(b []byte) error {
	var res Version
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
