// Code generated by go-swagger; DO NOT EDIT.

package trusted_network_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAllTrustedNetworksUsingGET1Params creates a new GetAllTrustedNetworksUsingGET1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllTrustedNetworksUsingGET1Params() *GetAllTrustedNetworksUsingGET1Params {
	return &GetAllTrustedNetworksUsingGET1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllTrustedNetworksUsingGET1ParamsWithTimeout creates a new GetAllTrustedNetworksUsingGET1Params object
// with the ability to set a timeout on a request.
func NewGetAllTrustedNetworksUsingGET1ParamsWithTimeout(timeout time.Duration) *GetAllTrustedNetworksUsingGET1Params {
	return &GetAllTrustedNetworksUsingGET1Params{
		timeout: timeout,
	}
}

// NewGetAllTrustedNetworksUsingGET1ParamsWithContext creates a new GetAllTrustedNetworksUsingGET1Params object
// with the ability to set a context for a request.
func NewGetAllTrustedNetworksUsingGET1ParamsWithContext(ctx context.Context) *GetAllTrustedNetworksUsingGET1Params {
	return &GetAllTrustedNetworksUsingGET1Params{
		Context: ctx,
	}
}

// NewGetAllTrustedNetworksUsingGET1ParamsWithHTTPClient creates a new GetAllTrustedNetworksUsingGET1Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllTrustedNetworksUsingGET1ParamsWithHTTPClient(client *http.Client) *GetAllTrustedNetworksUsingGET1Params {
	return &GetAllTrustedNetworksUsingGET1Params{
		HTTPClient: client,
	}
}

/* GetAllTrustedNetworksUsingGET1Params contains all the parameters to send to the API endpoint
   for the get all trusted networks using g e t 1 operation.

   Typically these are written to a http.Request.
*/
type GetAllTrustedNetworksUsingGET1Params struct {

	/* CustomerID.

	   The unique identifier of the ZPA tenant.

	   Format: int64
	*/
	CustomerID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all trusted networks using g e t 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllTrustedNetworksUsingGET1Params) WithDefaults() *GetAllTrustedNetworksUsingGET1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all trusted networks using g e t 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllTrustedNetworksUsingGET1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all trusted networks using g e t 1 params
func (o *GetAllTrustedNetworksUsingGET1Params) WithTimeout(timeout time.Duration) *GetAllTrustedNetworksUsingGET1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all trusted networks using g e t 1 params
func (o *GetAllTrustedNetworksUsingGET1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all trusted networks using g e t 1 params
func (o *GetAllTrustedNetworksUsingGET1Params) WithContext(ctx context.Context) *GetAllTrustedNetworksUsingGET1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all trusted networks using g e t 1 params
func (o *GetAllTrustedNetworksUsingGET1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all trusted networks using g e t 1 params
func (o *GetAllTrustedNetworksUsingGET1Params) WithHTTPClient(client *http.Client) *GetAllTrustedNetworksUsingGET1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all trusted networks using g e t 1 params
func (o *GetAllTrustedNetworksUsingGET1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the get all trusted networks using g e t 1 params
func (o *GetAllTrustedNetworksUsingGET1Params) WithCustomerID(customerID int64) *GetAllTrustedNetworksUsingGET1Params {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the get all trusted networks using g e t 1 params
func (o *GetAllTrustedNetworksUsingGET1Params) SetCustomerID(customerID int64) {
	o.CustomerID = customerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllTrustedNetworksUsingGET1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerId
	if err := r.SetPathParam("customerId", swag.FormatInt64(o.CustomerID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
