// Code generated by go-swagger; DO NOT EDIT.

package saml_attr_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllAttributesUsingGET4Params creates a new GetAllAttributesUsingGET4Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllAttributesUsingGET4Params() *GetAllAttributesUsingGET4Params {
	return &GetAllAttributesUsingGET4Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllAttributesUsingGET4ParamsWithTimeout creates a new GetAllAttributesUsingGET4Params object
// with the ability to set a timeout on a request.
func NewGetAllAttributesUsingGET4ParamsWithTimeout(timeout time.Duration) *GetAllAttributesUsingGET4Params {
	return &GetAllAttributesUsingGET4Params{
		timeout: timeout,
	}
}

// NewGetAllAttributesUsingGET4ParamsWithContext creates a new GetAllAttributesUsingGET4Params object
// with the ability to set a context for a request.
func NewGetAllAttributesUsingGET4ParamsWithContext(ctx context.Context) *GetAllAttributesUsingGET4Params {
	return &GetAllAttributesUsingGET4Params{
		Context: ctx,
	}
}

// NewGetAllAttributesUsingGET4ParamsWithHTTPClient creates a new GetAllAttributesUsingGET4Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllAttributesUsingGET4ParamsWithHTTPClient(client *http.Client) *GetAllAttributesUsingGET4Params {
	return &GetAllAttributesUsingGET4Params{
		HTTPClient: client,
	}
}

/* GetAllAttributesUsingGET4Params contains all the parameters to send to the API endpoint
   for the get all attributes using g e t 4 operation.

   Typically these are written to a http.Request.
*/
type GetAllAttributesUsingGET4Params struct {

	/* CustomerID.

	   The unique identifier of the ZPA tenant.
	*/
	CustomerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all attributes using g e t 4 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllAttributesUsingGET4Params) WithDefaults() *GetAllAttributesUsingGET4Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all attributes using g e t 4 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllAttributesUsingGET4Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all attributes using g e t 4 params
func (o *GetAllAttributesUsingGET4Params) WithTimeout(timeout time.Duration) *GetAllAttributesUsingGET4Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all attributes using g e t 4 params
func (o *GetAllAttributesUsingGET4Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all attributes using g e t 4 params
func (o *GetAllAttributesUsingGET4Params) WithContext(ctx context.Context) *GetAllAttributesUsingGET4Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all attributes using g e t 4 params
func (o *GetAllAttributesUsingGET4Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all attributes using g e t 4 params
func (o *GetAllAttributesUsingGET4Params) WithHTTPClient(client *http.Client) *GetAllAttributesUsingGET4Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all attributes using g e t 4 params
func (o *GetAllAttributesUsingGET4Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the get all attributes using g e t 4 params
func (o *GetAllAttributesUsingGET4Params) WithCustomerID(customerID string) *GetAllAttributesUsingGET4Params {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the get all attributes using g e t 4 params
func (o *GetAllAttributesUsingGET4Params) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllAttributesUsingGET4Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerId
	if err := r.SetPathParam("customerId", o.CustomerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
