// Code generated by go-swagger; DO NOT EDIT.

package saml_attr_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haarchri/zpa-go-client/pkg/models"
)

// GetSamlAttributeUsingGET1Reader is a Reader for the GetSamlAttributeUsingGET1 structure.
type GetSamlAttributeUsingGET1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSamlAttributeUsingGET1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSamlAttributeUsingGET1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetSamlAttributeUsingGET1BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetSamlAttributeUsingGET1Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetSamlAttributeUsingGET1Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetSamlAttributeUsingGET1NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetSamlAttributeUsingGET1TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSamlAttributeUsingGET1OK creates a GetSamlAttributeUsingGET1OK with default headers values
func NewGetSamlAttributeUsingGET1OK() *GetSamlAttributeUsingGET1OK {
	return &GetSamlAttributeUsingGET1OK{}
}

/* GetSamlAttributeUsingGET1OK describes a response with status code 200, with default header values.

OK
*/
type GetSamlAttributeUsingGET1OK struct {
	Payload *models.SamlAttribute
}

func (o *GetSamlAttributeUsingGET1OK) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/samlAttribute/{attrId}][%d] getSamlAttributeUsingGET1OK  %+v", 200, o.Payload)
}
func (o *GetSamlAttributeUsingGET1OK) GetPayload() *models.SamlAttribute {
	return o.Payload
}

func (o *GetSamlAttributeUsingGET1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SamlAttribute)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSamlAttributeUsingGET1BadRequest creates a GetSamlAttributeUsingGET1BadRequest with default headers values
func NewGetSamlAttributeUsingGET1BadRequest() *GetSamlAttributeUsingGET1BadRequest {
	return &GetSamlAttributeUsingGET1BadRequest{}
}

/* GetSamlAttributeUsingGET1BadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type GetSamlAttributeUsingGET1BadRequest struct {
}

func (o *GetSamlAttributeUsingGET1BadRequest) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/samlAttribute/{attrId}][%d] getSamlAttributeUsingGET1BadRequest ", 400)
}

func (o *GetSamlAttributeUsingGET1BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSamlAttributeUsingGET1Unauthorized creates a GetSamlAttributeUsingGET1Unauthorized with default headers values
func NewGetSamlAttributeUsingGET1Unauthorized() *GetSamlAttributeUsingGET1Unauthorized {
	return &GetSamlAttributeUsingGET1Unauthorized{}
}

/* GetSamlAttributeUsingGET1Unauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetSamlAttributeUsingGET1Unauthorized struct {
}

func (o *GetSamlAttributeUsingGET1Unauthorized) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/samlAttribute/{attrId}][%d] getSamlAttributeUsingGET1Unauthorized ", 401)
}

func (o *GetSamlAttributeUsingGET1Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSamlAttributeUsingGET1Forbidden creates a GetSamlAttributeUsingGET1Forbidden with default headers values
func NewGetSamlAttributeUsingGET1Forbidden() *GetSamlAttributeUsingGET1Forbidden {
	return &GetSamlAttributeUsingGET1Forbidden{}
}

/* GetSamlAttributeUsingGET1Forbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetSamlAttributeUsingGET1Forbidden struct {
}

func (o *GetSamlAttributeUsingGET1Forbidden) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/samlAttribute/{attrId}][%d] getSamlAttributeUsingGET1Forbidden ", 403)
}

func (o *GetSamlAttributeUsingGET1Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSamlAttributeUsingGET1NotFound creates a GetSamlAttributeUsingGET1NotFound with default headers values
func NewGetSamlAttributeUsingGET1NotFound() *GetSamlAttributeUsingGET1NotFound {
	return &GetSamlAttributeUsingGET1NotFound{}
}

/* GetSamlAttributeUsingGET1NotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetSamlAttributeUsingGET1NotFound struct {
}

func (o *GetSamlAttributeUsingGET1NotFound) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/samlAttribute/{attrId}][%d] getSamlAttributeUsingGET1NotFound ", 404)
}

func (o *GetSamlAttributeUsingGET1NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSamlAttributeUsingGET1TooManyRequests creates a GetSamlAttributeUsingGET1TooManyRequests with default headers values
func NewGetSamlAttributeUsingGET1TooManyRequests() *GetSamlAttributeUsingGET1TooManyRequests {
	return &GetSamlAttributeUsingGET1TooManyRequests{}
}

/* GetSamlAttributeUsingGET1TooManyRequests describes a response with status code 429, with default header values.

TooManyRequest
*/
type GetSamlAttributeUsingGET1TooManyRequests struct {
}

func (o *GetSamlAttributeUsingGET1TooManyRequests) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/samlAttribute/{attrId}][%d] getSamlAttributeUsingGET1TooManyRequests ", 429)
}

func (o *GetSamlAttributeUsingGET1TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
