// Code generated by go-swagger; DO NOT EDIT.

package saml_attr_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haarchri/zpa-go-client/pkg/models"
)

// GetAllAttributesUsingGET3Reader is a Reader for the GetAllAttributesUsingGET3 structure.
type GetAllAttributesUsingGET3Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllAttributesUsingGET3Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllAttributesUsingGET3OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAllAttributesUsingGET3Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAllAttributesUsingGET3Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAllAttributesUsingGET3NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllAttributesUsingGET3OK creates a GetAllAttributesUsingGET3OK with default headers values
func NewGetAllAttributesUsingGET3OK() *GetAllAttributesUsingGET3OK {
	return &GetAllAttributesUsingGET3OK{}
}

/* GetAllAttributesUsingGET3OK describes a response with status code 200, with default header values.

OK
*/
type GetAllAttributesUsingGET3OK struct {
	Payload []*models.SamlAttribute
}

func (o *GetAllAttributesUsingGET3OK) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/samlAttribute][%d] getAllAttributesUsingGET3OK  %+v", 200, o.Payload)
}
func (o *GetAllAttributesUsingGET3OK) GetPayload() []*models.SamlAttribute {
	return o.Payload
}

func (o *GetAllAttributesUsingGET3OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllAttributesUsingGET3Unauthorized creates a GetAllAttributesUsingGET3Unauthorized with default headers values
func NewGetAllAttributesUsingGET3Unauthorized() *GetAllAttributesUsingGET3Unauthorized {
	return &GetAllAttributesUsingGET3Unauthorized{}
}

/* GetAllAttributesUsingGET3Unauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAllAttributesUsingGET3Unauthorized struct {
}

func (o *GetAllAttributesUsingGET3Unauthorized) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/samlAttribute][%d] getAllAttributesUsingGET3Unauthorized ", 401)
}

func (o *GetAllAttributesUsingGET3Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllAttributesUsingGET3Forbidden creates a GetAllAttributesUsingGET3Forbidden with default headers values
func NewGetAllAttributesUsingGET3Forbidden() *GetAllAttributesUsingGET3Forbidden {
	return &GetAllAttributesUsingGET3Forbidden{}
}

/* GetAllAttributesUsingGET3Forbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAllAttributesUsingGET3Forbidden struct {
}

func (o *GetAllAttributesUsingGET3Forbidden) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/samlAttribute][%d] getAllAttributesUsingGET3Forbidden ", 403)
}

func (o *GetAllAttributesUsingGET3Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllAttributesUsingGET3NotFound creates a GetAllAttributesUsingGET3NotFound with default headers values
func NewGetAllAttributesUsingGET3NotFound() *GetAllAttributesUsingGET3NotFound {
	return &GetAllAttributesUsingGET3NotFound{}
}

/* GetAllAttributesUsingGET3NotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAllAttributesUsingGET3NotFound struct {
}

func (o *GetAllAttributesUsingGET3NotFound) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/samlAttribute][%d] getAllAttributesUsingGET3NotFound ", 404)
}

func (o *GetAllAttributesUsingGET3NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
