// Code generated by go-swagger; DO NOT EDIT.

package service_edge_group_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/haarchri/zpa-go-client/pkg/models"
)

// NewAddServiceEdgeGroupUsingPOSTParams creates a new AddServiceEdgeGroupUsingPOSTParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddServiceEdgeGroupUsingPOSTParams() *AddServiceEdgeGroupUsingPOSTParams {
	return &AddServiceEdgeGroupUsingPOSTParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddServiceEdgeGroupUsingPOSTParamsWithTimeout creates a new AddServiceEdgeGroupUsingPOSTParams object
// with the ability to set a timeout on a request.
func NewAddServiceEdgeGroupUsingPOSTParamsWithTimeout(timeout time.Duration) *AddServiceEdgeGroupUsingPOSTParams {
	return &AddServiceEdgeGroupUsingPOSTParams{
		timeout: timeout,
	}
}

// NewAddServiceEdgeGroupUsingPOSTParamsWithContext creates a new AddServiceEdgeGroupUsingPOSTParams object
// with the ability to set a context for a request.
func NewAddServiceEdgeGroupUsingPOSTParamsWithContext(ctx context.Context) *AddServiceEdgeGroupUsingPOSTParams {
	return &AddServiceEdgeGroupUsingPOSTParams{
		Context: ctx,
	}
}

// NewAddServiceEdgeGroupUsingPOSTParamsWithHTTPClient creates a new AddServiceEdgeGroupUsingPOSTParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddServiceEdgeGroupUsingPOSTParamsWithHTTPClient(client *http.Client) *AddServiceEdgeGroupUsingPOSTParams {
	return &AddServiceEdgeGroupUsingPOSTParams{
		HTTPClient: client,
	}
}

/* AddServiceEdgeGroupUsingPOSTParams contains all the parameters to send to the API endpoint
   for the add service edge group using p o s t operation.

   Typically these are written to a http.Request.
*/
type AddServiceEdgeGroupUsingPOSTParams struct {

	/* CustomerID.

	   The unique identifier of the ZPA tenant.
	*/
	CustomerID string

	/* ServiceEdgeGroup.

	   The object of the Service Edge Group.
	*/
	ServiceEdgeGroup *models.ServiceEdgeGroup

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add service edge group using p o s t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddServiceEdgeGroupUsingPOSTParams) WithDefaults() *AddServiceEdgeGroupUsingPOSTParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add service edge group using p o s t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddServiceEdgeGroupUsingPOSTParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add service edge group using p o s t params
func (o *AddServiceEdgeGroupUsingPOSTParams) WithTimeout(timeout time.Duration) *AddServiceEdgeGroupUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add service edge group using p o s t params
func (o *AddServiceEdgeGroupUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add service edge group using p o s t params
func (o *AddServiceEdgeGroupUsingPOSTParams) WithContext(ctx context.Context) *AddServiceEdgeGroupUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add service edge group using p o s t params
func (o *AddServiceEdgeGroupUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add service edge group using p o s t params
func (o *AddServiceEdgeGroupUsingPOSTParams) WithHTTPClient(client *http.Client) *AddServiceEdgeGroupUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add service edge group using p o s t params
func (o *AddServiceEdgeGroupUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the add service edge group using p o s t params
func (o *AddServiceEdgeGroupUsingPOSTParams) WithCustomerID(customerID string) *AddServiceEdgeGroupUsingPOSTParams {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the add service edge group using p o s t params
func (o *AddServiceEdgeGroupUsingPOSTParams) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WithServiceEdgeGroup adds the serviceEdgeGroup to the add service edge group using p o s t params
func (o *AddServiceEdgeGroupUsingPOSTParams) WithServiceEdgeGroup(serviceEdgeGroup *models.ServiceEdgeGroup) *AddServiceEdgeGroupUsingPOSTParams {
	o.SetServiceEdgeGroup(serviceEdgeGroup)
	return o
}

// SetServiceEdgeGroup adds the serviceEdgeGroup to the add service edge group using p o s t params
func (o *AddServiceEdgeGroupUsingPOSTParams) SetServiceEdgeGroup(serviceEdgeGroup *models.ServiceEdgeGroup) {
	o.ServiceEdgeGroup = serviceEdgeGroup
}

// WriteToRequest writes these params to a swagger request
func (o *AddServiceEdgeGroupUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerId
	if err := r.SetPathParam("customerId", o.CustomerID); err != nil {
		return err
	}
	if o.ServiceEdgeGroup != nil {
		if err := r.SetBodyParam(o.ServiceEdgeGroup); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
