// Code generated by go-swagger; DO NOT EDIT.

package service_edge_group_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haarchri/zpa-go-client/pkg/models"
)

// AddServiceEdgeGroupUsingPOSTReader is a Reader for the AddServiceEdgeGroupUsingPOST structure.
type AddServiceEdgeGroupUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddServiceEdgeGroupUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAddServiceEdgeGroupUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddServiceEdgeGroupUsingPOSTBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAddServiceEdgeGroupUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAddServiceEdgeGroupUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAddServiceEdgeGroupUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewAddServiceEdgeGroupUsingPOSTTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddServiceEdgeGroupUsingPOSTCreated creates a AddServiceEdgeGroupUsingPOSTCreated with default headers values
func NewAddServiceEdgeGroupUsingPOSTCreated() *AddServiceEdgeGroupUsingPOSTCreated {
	return &AddServiceEdgeGroupUsingPOSTCreated{}
}

/* AddServiceEdgeGroupUsingPOSTCreated describes a response with status code 201, with default header values.

Created
*/
type AddServiceEdgeGroupUsingPOSTCreated struct {
	Payload *models.ServiceEdgeGroup
}

func (o *AddServiceEdgeGroupUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /mgmtconfig/v1/admin/customers/{customerId}/serviceEdgeGroup][%d] addServiceEdgeGroupUsingPOSTCreated  %+v", 201, o.Payload)
}
func (o *AddServiceEdgeGroupUsingPOSTCreated) GetPayload() *models.ServiceEdgeGroup {
	return o.Payload
}

func (o *AddServiceEdgeGroupUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceEdgeGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddServiceEdgeGroupUsingPOSTBadRequest creates a AddServiceEdgeGroupUsingPOSTBadRequest with default headers values
func NewAddServiceEdgeGroupUsingPOSTBadRequest() *AddServiceEdgeGroupUsingPOSTBadRequest {
	return &AddServiceEdgeGroupUsingPOSTBadRequest{}
}

/* AddServiceEdgeGroupUsingPOSTBadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type AddServiceEdgeGroupUsingPOSTBadRequest struct {
}

func (o *AddServiceEdgeGroupUsingPOSTBadRequest) Error() string {
	return fmt.Sprintf("[POST /mgmtconfig/v1/admin/customers/{customerId}/serviceEdgeGroup][%d] addServiceEdgeGroupUsingPOSTBadRequest ", 400)
}

func (o *AddServiceEdgeGroupUsingPOSTBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddServiceEdgeGroupUsingPOSTUnauthorized creates a AddServiceEdgeGroupUsingPOSTUnauthorized with default headers values
func NewAddServiceEdgeGroupUsingPOSTUnauthorized() *AddServiceEdgeGroupUsingPOSTUnauthorized {
	return &AddServiceEdgeGroupUsingPOSTUnauthorized{}
}

/* AddServiceEdgeGroupUsingPOSTUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type AddServiceEdgeGroupUsingPOSTUnauthorized struct {
}

func (o *AddServiceEdgeGroupUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /mgmtconfig/v1/admin/customers/{customerId}/serviceEdgeGroup][%d] addServiceEdgeGroupUsingPOSTUnauthorized ", 401)
}

func (o *AddServiceEdgeGroupUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddServiceEdgeGroupUsingPOSTForbidden creates a AddServiceEdgeGroupUsingPOSTForbidden with default headers values
func NewAddServiceEdgeGroupUsingPOSTForbidden() *AddServiceEdgeGroupUsingPOSTForbidden {
	return &AddServiceEdgeGroupUsingPOSTForbidden{}
}

/* AddServiceEdgeGroupUsingPOSTForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type AddServiceEdgeGroupUsingPOSTForbidden struct {
}

func (o *AddServiceEdgeGroupUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /mgmtconfig/v1/admin/customers/{customerId}/serviceEdgeGroup][%d] addServiceEdgeGroupUsingPOSTForbidden ", 403)
}

func (o *AddServiceEdgeGroupUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddServiceEdgeGroupUsingPOSTNotFound creates a AddServiceEdgeGroupUsingPOSTNotFound with default headers values
func NewAddServiceEdgeGroupUsingPOSTNotFound() *AddServiceEdgeGroupUsingPOSTNotFound {
	return &AddServiceEdgeGroupUsingPOSTNotFound{}
}

/* AddServiceEdgeGroupUsingPOSTNotFound describes a response with status code 404, with default header values.

Not Found
*/
type AddServiceEdgeGroupUsingPOSTNotFound struct {
}

func (o *AddServiceEdgeGroupUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /mgmtconfig/v1/admin/customers/{customerId}/serviceEdgeGroup][%d] addServiceEdgeGroupUsingPOSTNotFound ", 404)
}

func (o *AddServiceEdgeGroupUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddServiceEdgeGroupUsingPOSTTooManyRequests creates a AddServiceEdgeGroupUsingPOSTTooManyRequests with default headers values
func NewAddServiceEdgeGroupUsingPOSTTooManyRequests() *AddServiceEdgeGroupUsingPOSTTooManyRequests {
	return &AddServiceEdgeGroupUsingPOSTTooManyRequests{}
}

/* AddServiceEdgeGroupUsingPOSTTooManyRequests describes a response with status code 429, with default header values.

TooManyRequest
*/
type AddServiceEdgeGroupUsingPOSTTooManyRequests struct {
}

func (o *AddServiceEdgeGroupUsingPOSTTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /mgmtconfig/v1/admin/customers/{customerId}/serviceEdgeGroup][%d] addServiceEdgeGroupUsingPOSTTooManyRequests ", 429)
}

func (o *AddServiceEdgeGroupUsingPOSTTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
