// Code generated by go-swagger; DO NOT EDIT.

package service_edge_group_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haarchri/zpa-go-client/pkg/models"
)

// GetServiceEdgeGroupUsingGETReader is a Reader for the GetServiceEdgeGroupUsingGET structure.
type GetServiceEdgeGroupUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServiceEdgeGroupUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetServiceEdgeGroupUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetServiceEdgeGroupUsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetServiceEdgeGroupUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetServiceEdgeGroupUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetServiceEdgeGroupUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetServiceEdgeGroupUsingGETTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetServiceEdgeGroupUsingGETOK creates a GetServiceEdgeGroupUsingGETOK with default headers values
func NewGetServiceEdgeGroupUsingGETOK() *GetServiceEdgeGroupUsingGETOK {
	return &GetServiceEdgeGroupUsingGETOK{}
}

/* GetServiceEdgeGroupUsingGETOK describes a response with status code 200, with default header values.

OK
*/
type GetServiceEdgeGroupUsingGETOK struct {
	Payload *models.ServiceEdgeGroup
}

func (o *GetServiceEdgeGroupUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/serviceEdgeGroup/{serviceEdgeGroupId}][%d] getServiceEdgeGroupUsingGETOK  %+v", 200, o.Payload)
}
func (o *GetServiceEdgeGroupUsingGETOK) GetPayload() *models.ServiceEdgeGroup {
	return o.Payload
}

func (o *GetServiceEdgeGroupUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceEdgeGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetServiceEdgeGroupUsingGETBadRequest creates a GetServiceEdgeGroupUsingGETBadRequest with default headers values
func NewGetServiceEdgeGroupUsingGETBadRequest() *GetServiceEdgeGroupUsingGETBadRequest {
	return &GetServiceEdgeGroupUsingGETBadRequest{}
}

/* GetServiceEdgeGroupUsingGETBadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type GetServiceEdgeGroupUsingGETBadRequest struct {
}

func (o *GetServiceEdgeGroupUsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/serviceEdgeGroup/{serviceEdgeGroupId}][%d] getServiceEdgeGroupUsingGETBadRequest ", 400)
}

func (o *GetServiceEdgeGroupUsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetServiceEdgeGroupUsingGETUnauthorized creates a GetServiceEdgeGroupUsingGETUnauthorized with default headers values
func NewGetServiceEdgeGroupUsingGETUnauthorized() *GetServiceEdgeGroupUsingGETUnauthorized {
	return &GetServiceEdgeGroupUsingGETUnauthorized{}
}

/* GetServiceEdgeGroupUsingGETUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetServiceEdgeGroupUsingGETUnauthorized struct {
}

func (o *GetServiceEdgeGroupUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/serviceEdgeGroup/{serviceEdgeGroupId}][%d] getServiceEdgeGroupUsingGETUnauthorized ", 401)
}

func (o *GetServiceEdgeGroupUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetServiceEdgeGroupUsingGETForbidden creates a GetServiceEdgeGroupUsingGETForbidden with default headers values
func NewGetServiceEdgeGroupUsingGETForbidden() *GetServiceEdgeGroupUsingGETForbidden {
	return &GetServiceEdgeGroupUsingGETForbidden{}
}

/* GetServiceEdgeGroupUsingGETForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetServiceEdgeGroupUsingGETForbidden struct {
}

func (o *GetServiceEdgeGroupUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/serviceEdgeGroup/{serviceEdgeGroupId}][%d] getServiceEdgeGroupUsingGETForbidden ", 403)
}

func (o *GetServiceEdgeGroupUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetServiceEdgeGroupUsingGETNotFound creates a GetServiceEdgeGroupUsingGETNotFound with default headers values
func NewGetServiceEdgeGroupUsingGETNotFound() *GetServiceEdgeGroupUsingGETNotFound {
	return &GetServiceEdgeGroupUsingGETNotFound{}
}

/* GetServiceEdgeGroupUsingGETNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetServiceEdgeGroupUsingGETNotFound struct {
}

func (o *GetServiceEdgeGroupUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/serviceEdgeGroup/{serviceEdgeGroupId}][%d] getServiceEdgeGroupUsingGETNotFound ", 404)
}

func (o *GetServiceEdgeGroupUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetServiceEdgeGroupUsingGETTooManyRequests creates a GetServiceEdgeGroupUsingGETTooManyRequests with default headers values
func NewGetServiceEdgeGroupUsingGETTooManyRequests() *GetServiceEdgeGroupUsingGETTooManyRequests {
	return &GetServiceEdgeGroupUsingGETTooManyRequests{}
}

/* GetServiceEdgeGroupUsingGETTooManyRequests describes a response with status code 429, with default header values.

TooManyRequest
*/
type GetServiceEdgeGroupUsingGETTooManyRequests struct {
}

func (o *GetServiceEdgeGroupUsingGETTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/serviceEdgeGroup/{serviceEdgeGroupId}][%d] getServiceEdgeGroupUsingGETTooManyRequests ", 429)
}

func (o *GetServiceEdgeGroupUsingGETTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
