// Code generated by go-swagger; DO NOT EDIT.

package enrollment_cert_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haarchri/zpa-go-client/pkg/models"
)

// GetEnrollmentCertUsingGET3Reader is a Reader for the GetEnrollmentCertUsingGET3 structure.
type GetEnrollmentCertUsingGET3Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEnrollmentCertUsingGET3Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEnrollmentCertUsingGET3OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetEnrollmentCertUsingGET3BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetEnrollmentCertUsingGET3Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetEnrollmentCertUsingGET3Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetEnrollmentCertUsingGET3NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetEnrollmentCertUsingGET3TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetEnrollmentCertUsingGET3OK creates a GetEnrollmentCertUsingGET3OK with default headers values
func NewGetEnrollmentCertUsingGET3OK() *GetEnrollmentCertUsingGET3OK {
	return &GetEnrollmentCertUsingGET3OK{}
}

/* GetEnrollmentCertUsingGET3OK describes a response with status code 200, with default header values.

OK
*/
type GetEnrollmentCertUsingGET3OK struct {
	Payload *models.EnrollmentCert
}

func (o *GetEnrollmentCertUsingGET3OK) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/enrollmentCert/{enrollmentCertId}][%d] getEnrollmentCertUsingGET3OK  %+v", 200, o.Payload)
}
func (o *GetEnrollmentCertUsingGET3OK) GetPayload() *models.EnrollmentCert {
	return o.Payload
}

func (o *GetEnrollmentCertUsingGET3OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EnrollmentCert)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEnrollmentCertUsingGET3BadRequest creates a GetEnrollmentCertUsingGET3BadRequest with default headers values
func NewGetEnrollmentCertUsingGET3BadRequest() *GetEnrollmentCertUsingGET3BadRequest {
	return &GetEnrollmentCertUsingGET3BadRequest{}
}

/* GetEnrollmentCertUsingGET3BadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type GetEnrollmentCertUsingGET3BadRequest struct {
}

func (o *GetEnrollmentCertUsingGET3BadRequest) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/enrollmentCert/{enrollmentCertId}][%d] getEnrollmentCertUsingGET3BadRequest ", 400)
}

func (o *GetEnrollmentCertUsingGET3BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetEnrollmentCertUsingGET3Unauthorized creates a GetEnrollmentCertUsingGET3Unauthorized with default headers values
func NewGetEnrollmentCertUsingGET3Unauthorized() *GetEnrollmentCertUsingGET3Unauthorized {
	return &GetEnrollmentCertUsingGET3Unauthorized{}
}

/* GetEnrollmentCertUsingGET3Unauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetEnrollmentCertUsingGET3Unauthorized struct {
}

func (o *GetEnrollmentCertUsingGET3Unauthorized) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/enrollmentCert/{enrollmentCertId}][%d] getEnrollmentCertUsingGET3Unauthorized ", 401)
}

func (o *GetEnrollmentCertUsingGET3Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetEnrollmentCertUsingGET3Forbidden creates a GetEnrollmentCertUsingGET3Forbidden with default headers values
func NewGetEnrollmentCertUsingGET3Forbidden() *GetEnrollmentCertUsingGET3Forbidden {
	return &GetEnrollmentCertUsingGET3Forbidden{}
}

/* GetEnrollmentCertUsingGET3Forbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetEnrollmentCertUsingGET3Forbidden struct {
}

func (o *GetEnrollmentCertUsingGET3Forbidden) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/enrollmentCert/{enrollmentCertId}][%d] getEnrollmentCertUsingGET3Forbidden ", 403)
}

func (o *GetEnrollmentCertUsingGET3Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetEnrollmentCertUsingGET3NotFound creates a GetEnrollmentCertUsingGET3NotFound with default headers values
func NewGetEnrollmentCertUsingGET3NotFound() *GetEnrollmentCertUsingGET3NotFound {
	return &GetEnrollmentCertUsingGET3NotFound{}
}

/* GetEnrollmentCertUsingGET3NotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetEnrollmentCertUsingGET3NotFound struct {
}

func (o *GetEnrollmentCertUsingGET3NotFound) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/enrollmentCert/{enrollmentCertId}][%d] getEnrollmentCertUsingGET3NotFound ", 404)
}

func (o *GetEnrollmentCertUsingGET3NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetEnrollmentCertUsingGET3TooManyRequests creates a GetEnrollmentCertUsingGET3TooManyRequests with default headers values
func NewGetEnrollmentCertUsingGET3TooManyRequests() *GetEnrollmentCertUsingGET3TooManyRequests {
	return &GetEnrollmentCertUsingGET3TooManyRequests{}
}

/* GetEnrollmentCertUsingGET3TooManyRequests describes a response with status code 429, with default header values.

TooManyRequest
*/
type GetEnrollmentCertUsingGET3TooManyRequests struct {
}

func (o *GetEnrollmentCertUsingGET3TooManyRequests) Error() string {
	return fmt.Sprintf("[GET /mgmtconfig/v1/admin/customers/{customerId}/enrollmentCert/{enrollmentCertId}][%d] getEnrollmentCertUsingGET3TooManyRequests ", 429)
}

func (o *GetEnrollmentCertUsingGET3TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
