// Code generated by go-swagger; DO NOT EDIT.

package connector_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteConnectorUsingDELETE1Reader is a Reader for the DeleteConnectorUsingDELETE1 structure.
type DeleteConnectorUsingDELETE1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteConnectorUsingDELETE1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteConnectorUsingDELETE1NoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteConnectorUsingDELETE1BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteConnectorUsingDELETE1Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteConnectorUsingDELETE1Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDeleteConnectorUsingDELETE1TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteConnectorUsingDELETE1NoContent creates a DeleteConnectorUsingDELETE1NoContent with default headers values
func NewDeleteConnectorUsingDELETE1NoContent() *DeleteConnectorUsingDELETE1NoContent {
	return &DeleteConnectorUsingDELETE1NoContent{}
}

/* DeleteConnectorUsingDELETE1NoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteConnectorUsingDELETE1NoContent struct {
}

func (o *DeleteConnectorUsingDELETE1NoContent) Error() string {
	return fmt.Sprintf("[DELETE /mgmtconfig/v1/admin/customers/{customerId}/connector/{connectorId}][%d] deleteConnectorUsingDELETE1NoContent ", 204)
}

func (o *DeleteConnectorUsingDELETE1NoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteConnectorUsingDELETE1BadRequest creates a DeleteConnectorUsingDELETE1BadRequest with default headers values
func NewDeleteConnectorUsingDELETE1BadRequest() *DeleteConnectorUsingDELETE1BadRequest {
	return &DeleteConnectorUsingDELETE1BadRequest{}
}

/* DeleteConnectorUsingDELETE1BadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type DeleteConnectorUsingDELETE1BadRequest struct {
}

func (o *DeleteConnectorUsingDELETE1BadRequest) Error() string {
	return fmt.Sprintf("[DELETE /mgmtconfig/v1/admin/customers/{customerId}/connector/{connectorId}][%d] deleteConnectorUsingDELETE1BadRequest ", 400)
}

func (o *DeleteConnectorUsingDELETE1BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteConnectorUsingDELETE1Unauthorized creates a DeleteConnectorUsingDELETE1Unauthorized with default headers values
func NewDeleteConnectorUsingDELETE1Unauthorized() *DeleteConnectorUsingDELETE1Unauthorized {
	return &DeleteConnectorUsingDELETE1Unauthorized{}
}

/* DeleteConnectorUsingDELETE1Unauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteConnectorUsingDELETE1Unauthorized struct {
}

func (o *DeleteConnectorUsingDELETE1Unauthorized) Error() string {
	return fmt.Sprintf("[DELETE /mgmtconfig/v1/admin/customers/{customerId}/connector/{connectorId}][%d] deleteConnectorUsingDELETE1Unauthorized ", 401)
}

func (o *DeleteConnectorUsingDELETE1Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteConnectorUsingDELETE1Forbidden creates a DeleteConnectorUsingDELETE1Forbidden with default headers values
func NewDeleteConnectorUsingDELETE1Forbidden() *DeleteConnectorUsingDELETE1Forbidden {
	return &DeleteConnectorUsingDELETE1Forbidden{}
}

/* DeleteConnectorUsingDELETE1Forbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteConnectorUsingDELETE1Forbidden struct {
}

func (o *DeleteConnectorUsingDELETE1Forbidden) Error() string {
	return fmt.Sprintf("[DELETE /mgmtconfig/v1/admin/customers/{customerId}/connector/{connectorId}][%d] deleteConnectorUsingDELETE1Forbidden ", 403)
}

func (o *DeleteConnectorUsingDELETE1Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteConnectorUsingDELETE1TooManyRequests creates a DeleteConnectorUsingDELETE1TooManyRequests with default headers values
func NewDeleteConnectorUsingDELETE1TooManyRequests() *DeleteConnectorUsingDELETE1TooManyRequests {
	return &DeleteConnectorUsingDELETE1TooManyRequests{}
}

/* DeleteConnectorUsingDELETE1TooManyRequests describes a response with status code 429, with default header values.

TooManyRequest
*/
type DeleteConnectorUsingDELETE1TooManyRequests struct {
}

func (o *DeleteConnectorUsingDELETE1TooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /mgmtconfig/v1/admin/customers/{customerId}/connector/{connectorId}][%d] deleteConnectorUsingDELETE1TooManyRequests ", 429)
}

func (o *DeleteConnectorUsingDELETE1TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
